# Generated by Django 6.0 on 2026-01-19 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('journal', '0001_initial'),
        ('teams', '0005_invitation_archived_at_membership_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Date this item was archived', null=True)),
                ('plaid_item_id', models.CharField(help_text="Plaid's unique identifier for this item", max_length=255, unique=True)),
                ('access_token', models.CharField(help_text='Access token for Plaid API', max_length=512)),
                ('institution_name', models.CharField(help_text='Name of the financial institution', max_length=255)),
                ('cursor', models.CharField(blank=True, help_text='Cursor for incremental transaction sync', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this item is currently active')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Plaid Item',
                'verbose_name_plural': 'Plaid Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Date this item was archived', null=True)),
                ('plaid_account_id', models.CharField(help_text="Plaid's unique identifier for this account", max_length=255, unique=True)),
                ('name', models.CharField(help_text='Account name from Plaid', max_length=255)),
                ('mask', models.CharField(blank=True, help_text='Last 4 digits of account number', max_length=10)),
                ('subtype', models.CharField(help_text='Account subtype (e.g., checking, savings)', max_length=100)),
                ('type', models.CharField(help_text='Account type (e.g., depository, credit)', max_length=100)),
                ('account', models.ForeignKey(blank=True, help_text='Ledger account this Plaid account feeds into', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plaid_accounts', to='accounts.account')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('item', models.ForeignKey(help_text='The Plaid item this account belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='plaid.plaiditem')),
            ],
            options={
                'verbose_name': 'Plaid Account',
                'verbose_name_plural': 'Plaid Accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Date this item was archived', null=True)),
                ('plaid_transaction_id', models.CharField(help_text="Plaid's unique identifier for this transaction", max_length=255, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text="Transaction amount (positive = outflow, negative = inflow in Plaid's convention)", max_digits=12)),
                ('iso_currency_code', models.CharField(blank=True, help_text='ISO currency code', max_length=10, null=True)),
                ('unofficial_currency_code', models.CharField(blank=True, help_text='Unofficial currency code for non-standard currencies', max_length=10, null=True)),
                ('date', models.DateField(help_text='Transaction date')),
                ('authorized_date', models.DateField(blank=True, help_text='Authorization date', null=True)),
                ('pending', models.BooleanField(default=False, help_text='Whether this transaction is pending')),
                ('pending_transaction_id', models.CharField(blank=True, help_text='ID of the pending transaction this replaces', max_length=255, null=True)),
                ('name', models.CharField(help_text='Transaction description', max_length=255)),
                ('merchant_name', models.CharField(blank=True, help_text='Merchant name', max_length=255, null=True)),
                ('personal_finance_category', models.CharField(blank=True, help_text="Plaid's personal finance category", max_length=255, null=True)),
                ('personal_finance_category_id', models.CharField(blank=True, help_text="Plaid's personal finance category ID", max_length=255, null=True)),
                ('category_confidence', models.CharField(blank=True, help_text="Confidence level of Plaid's categorization", max_length=50, null=True)),
                ('payment_channel', models.CharField(blank=True, help_text='Payment channel', max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, help_text='Transaction type', max_length=50, null=True)),
                ('location', models.JSONField(blank=True, help_text='Transaction location data', null=True)),
                ('merchant_metadata', models.JSONField(blank=True, help_text='Merchant metadata', null=True)),
                ('raw', models.JSONField(help_text='Raw transaction data from Plaid')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry created from this transaction (null = uncategorized)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_transactions', to='journal.journalentry')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('plaid_account', models.ForeignKey(help_text='The Plaid account this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='plaid.plaidaccount')),
            ],
            options={
                'verbose_name': 'Imported Transaction',
                'verbose_name_plural': 'Imported Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['plaid_account', 'journal_entry'], name='plaid_impor_plaid_a_7fd067_idx'), models.Index(fields=['date'], name='plaid_impor_date_5f70fa_idx'), models.Index(fields=['pending'], name='plaid_impor_pending_eb2a89_idx')],
            },
        ),
    ]
