# Generated by Django 6.0 on 2026-01-19 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_feed', '0001_initial'),
        ('plaid', '0001_initial'),
        ('teams', '0005_invitation_archived_at_membership_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Date this item was archived', null=True)),
                ('plaid_transaction_id', models.CharField(help_text="Plaid's unique identifier for this transaction", max_length=255, unique=True)),
                ('iso_currency_code', models.CharField(blank=True, help_text='ISO currency code', max_length=10, null=True)),
                ('unofficial_currency_code', models.CharField(blank=True, help_text='Unofficial currency code for non-standard currencies', max_length=10, null=True)),
                ('authorized_date', models.DateField(blank=True, help_text='Authorization date', null=True)),
                ('pending', models.BooleanField(default=False, help_text='Whether this transaction is pending')),
                ('pending_transaction_id', models.CharField(blank=True, help_text='ID of the pending transaction this replaces', max_length=255, null=True)),
                ('personal_finance_category', models.CharField(blank=True, help_text="Plaid's personal finance category", max_length=255, null=True)),
                ('personal_finance_category_id', models.CharField(blank=True, help_text="Plaid's personal finance category ID", max_length=255, null=True)),
                ('category_confidence', models.CharField(blank=True, help_text="Confidence level of Plaid's categorization", max_length=50, null=True)),
                ('payment_channel', models.CharField(blank=True, help_text='Payment channel', max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, help_text='Transaction type', max_length=50, null=True)),
                ('location', models.JSONField(blank=True, help_text='Transaction location data', null=True)),
                ('merchant_metadata', models.JSONField(blank=True, help_text='Merchant metadata', null=True)),
            ],
            options={
                'verbose_name': 'Plaid Transaction',
                'verbose_name_plural': 'Plaid Transactions',
                'ordering': ['-bank_transaction__posted_date'],
            },
        ),
        migrations.RemoveIndex(
            model_name='importedtransaction',
            name='plaid_impor_plaid_a_7fd067_idx',
        ),
        migrations.RemoveIndex(
            model_name='importedtransaction',
            name='plaid_impor_date_5f70fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='importedtransaction',
            name='plaid_impor_pending_eb2a89_idx',
        ),
        migrations.RemoveField(
            model_name='plaiditem',
            name='is_active',
        ),
        migrations.AddField(
            model_name='plaidtransaction',
            name='bank_transaction',
            field=models.OneToOneField(help_text='The bank transaction this plaid transaction is linked to', on_delete=django.db.models.deletion.CASCADE, related_name='plaid_transaction', to='bank_feed.banktransaction'),
        ),
        migrations.AddField(
            model_name='plaidtransaction',
            name='plaid_account',
            field=models.ForeignKey(help_text='The Plaid account this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='plaid.plaidaccount'),
        ),
        migrations.AddField(
            model_name='plaidtransaction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team'),
        ),
        migrations.RemoveField(
            model_name='importedtransaction',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='importedtransaction',
            name='plaid_account',
        ),
        migrations.RemoveField(
            model_name='importedtransaction',
            name='team',
        ),
        migrations.AddIndex(
            model_name='plaidtransaction',
            index=models.Index(fields=['plaid_account'], name='plaid_plaid_plaid_a_0305e1_idx'),
        ),
        migrations.AddIndex(
            model_name='plaidtransaction',
            index=models.Index(fields=['pending'], name='plaid_plaid_pending_b9708c_idx'),
        ),
        migrations.DeleteModel(
            name='ImportedTransaction',
        ),
    ]
