# Generated by Django 6.0 on 2026-01-12 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_payee_id_payee_id'),
        ('plaid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidaccount',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Ledger account this Plaid account feeds into', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plaid_accounts', to='accounts.account'),
        ),
    ]
