# Generated by Django 6.0 on 2026-06-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plaid", "0002_plaidtransaction_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plaiditem",
            name="last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When transactions were last successfully synced from Plaid",
                null=True,
            ),
        ),
    ]
