# Generated by Django 5.2.8 on 2025-12-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payee',
            old_name='payee_id',
            new_name='id',
        ),
    ]
