# Generated by Django 6.0 on 2026-05-28 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_accountgroup_account_type"),
        ("teams", "0005_invitation_archived_at_membership_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Set to true to archive this item"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="Date this item was archived", null=True
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("team", "name")},
            },
        ),
        migrations.AddField(
            model_name="account",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                help_text="Bank or financial institution this account is held with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="accounts.institution",
            ),
        ),
    ]
