# Generated by Django 6.0 on 2026-05-28 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_institution_account_institution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="account",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="account",
            name="account_number",
        ),
    ]
