# Generated by Django 6.0 on 2026-05-28 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_account_number"),
        ("teams", "0005_invitation_archived_at_membership_archived_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={
                "ordering": [
                    "account_group__account_type",
                    "account_group__name",
                    "name",
                ]
            },
        ),
    ]
