# Generated by Django 6.0 on 2026-05-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_unique_name_and_ordering"),
    ]

    operations = []
