# Generated by Django 6.0 on 2026-06-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_account_remove_unique_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="System accounts cannot be deleted by users"
            ),
        ),
        migrations.AddField(
            model_name="accountgroup",
            name="is_system",
            field=models.BooleanField(
                default=False, help_text="System groups cannot be deleted by users"
            ),
        ),
    ]
