# Generated by Django 6.0 on 2026-10-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_account_hidden_from_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_hidden",
            field=models.BooleanField(
                default=False,
                help_text="Left out of every account picker and the Inbox. A display choice only: its transactions and balance still count everywhere.",
            ),
        ),
    ]
