# Generated by Django 6.0 on 2026-01-19 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('journal', '0001_initial'),
        ('teams', '0005_invitation_archived_at_membership_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Date this item was archived', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive = outflow, negative = inflow in Plaid convention)', max_digits=12)),
                ('posted_date', models.DateField(help_text='Transaction date')),
                ('description', models.CharField(help_text='Transaction description', max_length=255)),
                ('merchant_name', models.CharField(blank=True, help_text='Merchant name', max_length=255, null=True)),
                ('source', models.CharField(choices=[('plaid', 'Plaid'), ('csv', 'CSV'), ('manual', 'Manual'), ('system', 'System')], default='plaid', help_text='Source of this imported transaction (plaid, csv, manual)', max_length=20)),
                ('raw', models.JSONField(blank=True, help_text='Raw transaction data from source', null=True)),
                ('account', models.ForeignKey(help_text='The account this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='accounts.account')),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry created from this transaction (null = uncategorized)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_feed_transactions', to='journal.journalentry')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Imported Transaction',
                'verbose_name_plural': 'Imported Transactions',
                'ordering': ['-posted_date', '-created_at'],
                'indexes': [models.Index(fields=['journal_entry'], name='bank_feed_b_journal_7255bf_idx'), models.Index(fields=['posted_date'], name='bank_feed_b_posted__0de569_idx'), models.Index(fields=['source'], name='bank_feed_b_source_217e80_idx')],
            },
        ),
    ]
