# Generated by Django 6.0 on 2026-01-15 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0004_journalline_reconciled_date'),
        ('plaid', '0002_alter_plaidaccount_account'),
        ('teams', '0004_invitation_is_archived_membership_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('source', models.CharField(choices=[('plaid', 'Plaid'), ('csv', 'CSV'), ('manual', 'Manual'), ('system', 'System')], default='plaid', help_text='Source of this imported transaction (plaid, csv, manual)', max_length=20)),
                ('plaid_transaction_id', models.CharField(blank=True, help_text="Plaid's unique identifier for this transaction (only for source=plaid)", max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount (positive = outflow, negative = inflow in Plaid convention)', max_digits=12)),
                ('iso_currency_code', models.CharField(blank=True, help_text='ISO currency code', max_length=10, null=True)),
                ('unofficial_currency_code', models.CharField(blank=True, help_text='Unofficial currency code for non-standard currencies', max_length=10, null=True)),
                ('date', models.DateField(help_text='Transaction date')),
                ('authorized_date', models.DateField(blank=True, help_text='Authorization date', null=True)),
                ('pending', models.BooleanField(default=False, help_text='Whether this transaction is pending')),
                ('pending_transaction_id', models.CharField(blank=True, help_text='ID of the pending transaction this replaces', max_length=255, null=True)),
                ('description', models.CharField(help_text='Transaction description', max_length=255)),
                ('merchant_name', models.CharField(blank=True, help_text='Merchant name', max_length=255, null=True)),
                ('plaid_category', models.CharField(blank=True, help_text="Plaid's personal finance category", max_length=255, null=True)),
                ('plaid_category_id', models.CharField(blank=True, help_text="Plaid's personal finance category ID", max_length=255, null=True)),
                ('plaid_category_confidence', models.CharField(blank=True, help_text="Confidence level of Plaid's categorization", max_length=50, null=True)),
                ('payment_channel', models.CharField(blank=True, help_text='Payment channel', max_length=50, null=True)),
                ('transaction_type', models.CharField(blank=True, help_text='Transaction type', max_length=50, null=True)),
                ('location', models.JSONField(blank=True, help_text='Transaction location data', null=True)),
                ('merchant_metadata', models.JSONField(blank=True, help_text='Merchant metadata', null=True)),
                ('raw', models.JSONField(blank=True, help_text='Raw transaction data from source', null=True)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Journal entry created from this transaction (null = uncategorized)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_feed_transactions', to='journal.journalentry')),
                ('plaid_account', models.ForeignKey(blank=True, help_text='The Plaid account this transaction belongs to (only for source=plaid)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imported_transactions', to='plaid.plaidaccount')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Imported Transaction',
                'verbose_name_plural': 'Imported Transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['plaid_account', 'journal_entry'], name='bank_feed_b_plaid_a_32145e_idx'), models.Index(fields=['date'], name='bank_feed_b_date_a5d202_idx'), models.Index(fields=['pending'], name='bank_feed_b_pending_e54fa2_idx'), models.Index(fields=['source'], name='bank_feed_b_source_217e80_idx')],
            },
        ),
    ]
