# Generated by Django 6.0 on 2026-01-15 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_payee_id_payee_id'),
        ('bank_feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='account',
            field=models.ForeignKey(default=1000, help_text='The account this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='accounts.account'),
            preserve_default=False,
        ),
    ]
