# Generated by Django 6.0 on 2026-01-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-posted_date', '-created_at'], 'verbose_name': 'Bank Transaction', 'verbose_name_plural': 'Bank Transactions'},
        ),
    ]
