# Generated by Django 6.0 on 2026-06-16 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_feed", "0002_alter_banktransaction_options"),
        ("teams", "0005_invitation_archived_at_membership_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferMatchDismissal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Set to true to archive this item"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="Date this item was archived", null=True
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
                (
                    "transaction_high",
                    models.ForeignKey(
                        help_text="The paired transaction with the higher id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_dismissals_as_high",
                        to="bank_feed.banktransaction",
                    ),
                ),
                (
                    "transaction_low",
                    models.ForeignKey(
                        help_text="The paired transaction with the lower id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_dismissals_as_low",
                        to="bank_feed.banktransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transfer Match Dismissal",
                "verbose_name_plural": "Transfer Match Dismissals",
                "unique_together": {("team", "transaction_low", "transaction_high")},
            },
        ),
    ]
