# Generated by Django 6.0 on 2026-06-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_feed", "0003_transfermatchdismissal"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="is_transfer_mirror",
            field=models.BooleanField(
                default=False,
                help_text="True if this row is the auto-created counterpart leg of a transfer",
            ),
        ),
    ]
