# Generated by Django 6.0 on 2026-09-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_feed", "0006_book_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banktransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("plaid", "Plaid"),
                    ("csv", "CSV"),
                    ("manual", "Manual"),
                    ("system", "System"),
                    ("ynab", "YNAB"),
                ],
                default="plaid",
                help_text="Source of this imported transaction (plaid, csv, manual)",
                max_length=20,
            ),
        ),
    ]
