# Generated by Django 6.0 on 2026-09-19 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0005_invitation_archived_at_membership_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YnabImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Set to true to archive this item"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="Date this item was archived", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "register_csv",
                    models.TextField(
                        blank=True,
                        help_text="The uploaded register export, cleared once applied.",
                    ),
                ),
                (
                    "plan_csv",
                    models.TextField(
                        blank=True,
                        help_text="The uploaded plan export, cleared once applied.",
                    ),
                ),
                (
                    "choices",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The wizard's answers: account types, income mapping, which savings categories are goals.",
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="What was written, and how the reconciliation came out.",
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="The Celery task running this import.",
                        max_length=255,
                    ),
                ),
                (
                    "progress",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Percent complete, for the wizard's apply screen.",
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        blank=True,
                        help_text="What the import is doing right now.",
                        max_length=100,
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ynab_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "verbose_name": "YNAB import",
                "verbose_name_plural": "YNAB imports",
                "ordering": ["-created_at"],
            },
        ),
    ]
