# Generated by Django 6.0 on 2026-09-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ynab_import", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ynabimport",
            name="started_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the worker picked this import up.",
                null=True,
            ),
        ),
    ]
