/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuditEvent,
  PaginatedAuditEventList,
} from '../models/index';
import {
    AuditEventFromJSON,
    AuditEventToJSON,
    PaginatedAuditEventListFromJSON,
    PaginatedAuditEventListToJSON,
} from '../models/index';

export interface AuditEventsListRequest {
    bookSlug: string;
    teamSlug: string;
    eventType?: string;
    page?: number;
}

export interface AuditEventsRetrieveRequest {
    bookSlug: string;
    id: number;
    teamSlug: string;
}

/**
 * 
 */
export class AuditApi extends runtime.BaseAPI {

    /**
     */
    async auditEventsListRaw(requestParameters: AuditEventsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedAuditEventList>> {
        if (requestParameters['bookSlug'] == null) {
            throw new runtime.RequiredError(
                'bookSlug',
                'Required parameter "bookSlug" was null or undefined when calling auditEventsList().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling auditEventsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['eventType'] != null) {
            queryParameters['event_type'] = requestParameters['eventType'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/{book_slug}/audit/api/events/`.replace(`{${"book_slug"}}`, encodeURIComponent(String(requestParameters['bookSlug']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedAuditEventListFromJSON(jsonValue));
    }

    /**
     */
    async auditEventsList(requestParameters: AuditEventsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedAuditEventList> {
        const response = await this.auditEventsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async auditEventsRetrieveRaw(requestParameters: AuditEventsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuditEvent>> {
        if (requestParameters['bookSlug'] == null) {
            throw new runtime.RequiredError(
                'bookSlug',
                'Required parameter "bookSlug" was null or undefined when calling auditEventsRetrieve().'
            );
        }

        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling auditEventsRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling auditEventsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/{book_slug}/audit/api/events/{id}/`.replace(`{${"book_slug"}}`, encodeURIComponent(String(requestParameters['bookSlug']))).replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuditEventFromJSON(jsonValue));
    }

    /**
     */
    async auditEventsRetrieve(requestParameters: AuditEventsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuditEvent> {
        const response = await this.auditEventsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
