/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BankFeedRow,
  CategorizeTransactionsRequest,
  PaginatedBankFeedRowList,
} from '../models/index';
import {
    BankFeedRowFromJSON,
    BankFeedRowToJSON,
    CategorizeTransactionsRequestFromJSON,
    CategorizeTransactionsRequestToJSON,
    PaginatedBankFeedRowListFromJSON,
    PaginatedBankFeedRowListToJSON,
} from '../models/index';

export interface BankFeedFeedListRequest {
    teamSlug: string;
    account?: number;
    page?: number;
}

export interface BankFeedFeedRetrieveRequest {
    id: string;
    teamSlug: string;
}

export interface BankFeedTransactionsCategorizeRequest {
    teamSlug: string;
    categorizeTransactionsRequest: CategorizeTransactionsRequest;
}

/**
 * 
 */
export class BankFeedApi extends runtime.BaseAPI {

    /**
     * Get unified bank feed, optionally filtered by account. Query params: - account: Account ID to filter by (optional)
     */
    async bankFeedFeedListRaw(requestParameters: BankFeedFeedListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedBankFeedRowList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling bankFeedFeedList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/bankfeed/api/feed/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedBankFeedRowListFromJSON(jsonValue));
    }

    /**
     * Get unified bank feed, optionally filtered by account. Query params: - account: Account ID to filter by (optional)
     */
    async bankFeedFeedList(requestParameters: BankFeedFeedListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedBankFeedRowList> {
        const response = await this.bankFeedFeedListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Unified bank feed API. Uses BankTransaction as the base unit, combining uncategorized BankTransactions (extended with PlaidTransaction data when applicable) and categorized BankTransactions showing category from linked JournalEntry.  - GET /a/{team_slug}/bankfeed/api/feed/ - Get all bank transactions - GET /a/{team_slug}/bankfeed/api/feed/{id}/ - Get transactions for specific account
     */
    async bankFeedFeedRetrieveRaw(requestParameters: BankFeedFeedRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BankFeedRow>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bankFeedFeedRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling bankFeedFeedRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/bankfeed/api/feed/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BankFeedRowFromJSON(jsonValue));
    }

    /**
     * Unified bank feed API. Uses BankTransaction as the base unit, combining uncategorized BankTransactions (extended with PlaidTransaction data when applicable) and categorized BankTransactions showing category from linked JournalEntry.  - GET /a/{team_slug}/bankfeed/api/feed/ - Get all bank transactions - GET /a/{team_slug}/bankfeed/api/feed/{id}/ - Get transactions for specific account
     */
    async bankFeedFeedRetrieve(requestParameters: BankFeedFeedRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BankFeedRow> {
        const response = await this.bankFeedFeedRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Categorize one or more bank transactions. Creates journal entries linking the bank account to the category account.  Body: - rows: List of transaction objects with \'id\' field - category_id: ID of the category account
     */
    async bankFeedTransactionsCategorizeRaw(requestParameters: BankFeedTransactionsCategorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling bankFeedTransactionsCategorize().'
            );
        }

        if (requestParameters['categorizeTransactionsRequest'] == null) {
            throw new runtime.RequiredError(
                'categorizeTransactionsRequest',
                'Required parameter "categorizeTransactionsRequest" was null or undefined when calling bankFeedTransactionsCategorize().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/bankfeed/api/feed/categorize/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CategorizeTransactionsRequestToJSON(requestParameters['categorizeTransactionsRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Categorize one or more bank transactions. Creates journal entries linking the bank account to the category account.  Body: - rows: List of transaction objects with \'id\' field - category_id: ID of the category account
     */
    async bankFeedTransactionsCategorize(requestParameters: BankFeedTransactionsCategorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.bankFeedTransactionsCategorizeRaw(requestParameters, initOverrides);
    }

}
