/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BankTransaction,
  CategorizeTransactionsRequest,
  PaginatedBankTransactionList,
} from '../models/index';
import {
    BankTransactionFromJSON,
    BankTransactionToJSON,
    CategorizeTransactionsRequestFromJSON,
    CategorizeTransactionsRequestToJSON,
    PaginatedBankTransactionListFromJSON,
    PaginatedBankTransactionListToJSON,
} from '../models/index';

export interface BankFeedTransactionsCategorizeRequest {
    teamSlug: string;
    categorizeTransactionsRequest: CategorizeTransactionsRequest;
}

export interface BankFeedTransactionsListRequest {
    teamSlug: string;
    account?: number;
    dateFrom?: string;
    dateTo?: string;
    isCategorized?: boolean;
    page?: number;
    pending?: boolean;
    source?: string;
}

export interface BankFeedTransactionsRetrieveRequest {
    id: string;
    teamSlug: string;
}

/**
 * 
 */
export class BankFeedApi extends runtime.BaseAPI {

    /**
     * Categorize one or more bank transactions. Creates journal entries linking the bank account to the category account.  Body: - rows: List of transaction objects with \'id\' field - category_account_id: ID of the category account
     */
    async bankFeedTransactionsCategorizeRaw(requestParameters: BankFeedTransactionsCategorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling bankFeedTransactionsCategorize().'
            );
        }

        if (requestParameters['categorizeTransactionsRequest'] == null) {
            throw new runtime.RequiredError(
                'categorizeTransactionsRequest',
                'Required parameter "categorizeTransactionsRequest" was null or undefined when calling bankFeedTransactionsCategorize().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/bankfeed/api/transactions/categorize/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CategorizeTransactionsRequestToJSON(requestParameters['categorizeTransactionsRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Categorize one or more bank transactions. Creates journal entries linking the bank account to the category account.  Body: - rows: List of transaction objects with \'id\' field - category_account_id: ID of the category account
     */
    async bankFeedTransactionsCategorize(requestParameters: BankFeedTransactionsCategorizeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.bankFeedTransactionsCategorizeRaw(requestParameters, initOverrides);
    }

    /**
     * ViewSet for BankTransaction model. Provides read-only access to imported transactions from all sources (Plaid, CSV, manual).
     */
    async bankFeedTransactionsListRaw(requestParameters: BankFeedTransactionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedBankTransactionList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling bankFeedTransactionsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['dateFrom'] != null) {
            queryParameters['date_from'] = requestParameters['dateFrom'];
        }

        if (requestParameters['dateTo'] != null) {
            queryParameters['date_to'] = requestParameters['dateTo'];
        }

        if (requestParameters['isCategorized'] != null) {
            queryParameters['is_categorized'] = requestParameters['isCategorized'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pending'] != null) {
            queryParameters['pending'] = requestParameters['pending'];
        }

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/bankfeed/api/transactions/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedBankTransactionListFromJSON(jsonValue));
    }

    /**
     * ViewSet for BankTransaction model. Provides read-only access to imported transactions from all sources (Plaid, CSV, manual).
     */
    async bankFeedTransactionsList(requestParameters: BankFeedTransactionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedBankTransactionList> {
        const response = await this.bankFeedTransactionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for BankTransaction model. Provides read-only access to imported transactions from all sources (Plaid, CSV, manual).
     */
    async bankFeedTransactionsRetrieveRaw(requestParameters: BankFeedTransactionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BankTransaction>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling bankFeedTransactionsRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling bankFeedTransactionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/bankfeed/api/transactions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BankTransactionFromJSON(jsonValue));
    }

    /**
     * ViewSet for BankTransaction model. Provides read-only access to imported transactions from all sources (Plaid, CSV, manual).
     */
    async bankFeedTransactionsRetrieve(requestParameters: BankFeedTransactionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BankTransaction> {
        const response = await this.bankFeedTransactionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
