/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JournalEntry,
  PaginatedJournalEntryList,
  PaginatedSimpleTransactionList,
  PatchedJournalEntry,
  PatchedSimpleTransaction,
  SimpleTransaction,
} from '../models/index';
import {
    JournalEntryFromJSON,
    JournalEntryToJSON,
    PaginatedJournalEntryListFromJSON,
    PaginatedJournalEntryListToJSON,
    PaginatedSimpleTransactionListFromJSON,
    PaginatedSimpleTransactionListToJSON,
    PatchedJournalEntryFromJSON,
    PatchedJournalEntryToJSON,
    PatchedSimpleTransactionFromJSON,
    PatchedSimpleTransactionToJSON,
    SimpleTransactionFromJSON,
    SimpleTransactionToJSON,
} from '../models/index';

export interface JournalEntriesCreateRequest {
    teamSlug: string;
    journalEntry: Omit<JournalEntry, 'id'|'payee_name'|'total_debits'|'total_credits'|'is_balanced'|'created_at'|'updated_at'>;
}

export interface JournalEntriesDestroyRequest {
    id: number;
    teamSlug: string;
}

export interface JournalEntriesListRequest {
    teamSlug: string;
    page?: number;
}

export interface JournalEntriesPartialUpdateRequest {
    id: number;
    teamSlug: string;
    patchedJournalEntry?: Omit<PatchedJournalEntry, 'id'|'payee_name'|'total_debits'|'total_credits'|'is_balanced'|'created_at'|'updated_at'>;
}

export interface JournalEntriesRetrieveRequest {
    id: number;
    teamSlug: string;
}

export interface JournalEntriesUpdateRequest {
    id: number;
    teamSlug: string;
    journalEntry: Omit<JournalEntry, 'id'|'payee_name'|'total_debits'|'total_credits'|'is_balanced'|'created_at'|'updated_at'>;
}

export interface SimpleTransactionsCreateRequest {
    teamSlug: string;
    simpleTransaction: Omit<SimpleTransaction, 'id'|'account_name'|'category_name'|'payee_name'|'status'|'created_at'|'updated_at'>;
}

export interface SimpleTransactionsDestroyRequest {
    id: number;
    teamSlug: string;
}

export interface SimpleTransactionsListRequest {
    teamSlug: string;
    page?: number;
}

export interface SimpleTransactionsPartialUpdateRequest {
    id: number;
    teamSlug: string;
    patchedSimpleTransaction?: Omit<PatchedSimpleTransaction, 'id'|'account_name'|'category_name'|'payee_name'|'status'|'created_at'|'updated_at'>;
}

export interface SimpleTransactionsRetrieveRequest {
    id: number;
    teamSlug: string;
}

export interface SimpleTransactionsUpdateRequest {
    id: number;
    teamSlug: string;
    simpleTransaction: Omit<SimpleTransaction, 'id'|'account_name'|'category_name'|'payee_name'|'status'|'created_at'|'updated_at'>;
}

/**
 * 
 */
export class JournalApi extends runtime.BaseAPI {

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesCreateRaw(requestParameters: JournalEntriesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JournalEntry>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesCreate().'
            );
        }

        if (requestParameters['journalEntry'] == null) {
            throw new runtime.RequiredError(
                'journalEntry',
                'Required parameter "journalEntry" was null or undefined when calling journalEntriesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JournalEntryToJSON(requestParameters['journalEntry']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesCreate(requestParameters: JournalEntriesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JournalEntry> {
        const response = await this.journalEntriesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesDestroyRaw(requestParameters: JournalEntriesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling journalEntriesDestroy().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesDestroy(requestParameters: JournalEntriesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.journalEntriesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesListRaw(requestParameters: JournalEntriesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedJournalEntryList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedJournalEntryListFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesList(requestParameters: JournalEntriesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedJournalEntryList> {
        const response = await this.journalEntriesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesPartialUpdateRaw(requestParameters: JournalEntriesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JournalEntry>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling journalEntriesPartialUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedJournalEntryToJSON(requestParameters['patchedJournalEntry']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesPartialUpdate(requestParameters: JournalEntriesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JournalEntry> {
        const response = await this.journalEntriesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesRetrieveRaw(requestParameters: JournalEntriesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JournalEntry>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling journalEntriesRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesRetrieve(requestParameters: JournalEntriesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JournalEntry> {
        const response = await this.journalEntriesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesUpdateRaw(requestParameters: JournalEntriesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JournalEntry>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling journalEntriesUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesUpdate().'
            );
        }

        if (requestParameters['journalEntry'] == null) {
            throw new runtime.RequiredError(
                'journalEntry',
                'Required parameter "journalEntry" was null or undefined when calling journalEntriesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: JournalEntryToJSON(requestParameters['journalEntry']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesUpdate(requestParameters: JournalEntriesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JournalEntry> {
        const response = await this.journalEntriesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsCreateRaw(requestParameters: SimpleTransactionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleTransaction>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleTransactionsCreate().'
            );
        }

        if (requestParameters['simpleTransaction'] == null) {
            throw new runtime.RequiredError(
                'simpleTransaction',
                'Required parameter "simpleTransaction" was null or undefined when calling simpleTransactionsCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/transactions/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimpleTransactionToJSON(requestParameters['simpleTransaction']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleTransactionFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsCreate(requestParameters: SimpleTransactionsCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleTransaction> {
        const response = await this.simpleTransactionsCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsDestroyRaw(requestParameters: SimpleTransactionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleTransactionsDestroy().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleTransactionsDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/transactions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsDestroy(requestParameters: SimpleTransactionsDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.simpleTransactionsDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsListRaw(requestParameters: SimpleTransactionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSimpleTransactionList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleTransactionsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/transactions/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSimpleTransactionListFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsList(requestParameters: SimpleTransactionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSimpleTransactionList> {
        const response = await this.simpleTransactionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsPartialUpdateRaw(requestParameters: SimpleTransactionsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleTransaction>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleTransactionsPartialUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleTransactionsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/transactions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedSimpleTransactionToJSON(requestParameters['patchedSimpleTransaction']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleTransactionFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsPartialUpdate(requestParameters: SimpleTransactionsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleTransaction> {
        const response = await this.simpleTransactionsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsRetrieveRaw(requestParameters: SimpleTransactionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleTransaction>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleTransactionsRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleTransactionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/transactions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleTransactionFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsRetrieve(requestParameters: SimpleTransactionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleTransaction> {
        const response = await this.simpleTransactionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsUpdateRaw(requestParameters: SimpleTransactionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleTransaction>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleTransactionsUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleTransactionsUpdate().'
            );
        }

        if (requestParameters['simpleTransaction'] == null) {
            throw new runtime.RequiredError(
                'simpleTransaction',
                'Required parameter "simpleTransaction" was null or undefined when calling simpleTransactionsUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/transactions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SimpleTransactionToJSON(requestParameters['simpleTransaction']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleTransactionFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified transaction interface. Provides CRUD operations for transactions using a simple format that gets converted to journal entries behind the scenes.  This is designed for client applications that want a simple transaction model without dealing with double-entry bookkeeping.
     */
    async simpleTransactionsUpdate(requestParameters: SimpleTransactionsUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleTransaction> {
        const response = await this.simpleTransactionsUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
