/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  JournalEntry,
  PaginatedJournalEntryList,
  PaginatedSimpleLineList,
  PatchedJournalEntry,
  PatchedSimpleLine,
  SimpleLine,
  SimpleLinesRecategorize200Response,
  SimpleLinesRecategorizeRequest,
} from '../models/index';
import {
    JournalEntryFromJSON,
    JournalEntryToJSON,
    PaginatedJournalEntryListFromJSON,
    PaginatedJournalEntryListToJSON,
    PaginatedSimpleLineListFromJSON,
    PaginatedSimpleLineListToJSON,
    PatchedJournalEntryFromJSON,
    PatchedJournalEntryToJSON,
    PatchedSimpleLineFromJSON,
    PatchedSimpleLineToJSON,
    SimpleLineFromJSON,
    SimpleLineToJSON,
    SimpleLinesRecategorize200ResponseFromJSON,
    SimpleLinesRecategorize200ResponseToJSON,
    SimpleLinesRecategorizeRequestFromJSON,
    SimpleLinesRecategorizeRequestToJSON,
} from '../models/index';

export interface JournalEntriesCreateRequest {
    teamSlug: string;
    journalEntry: Omit<JournalEntry, 'id'|'payee_name'|'total_debits'|'total_credits'|'is_balanced'|'created_at'|'updated_at'>;
}

export interface JournalEntriesDestroyRequest {
    id: string;
    teamSlug: string;
}

export interface JournalEntriesListRequest {
    teamSlug: string;
    page?: number;
}

export interface JournalEntriesPartialUpdateRequest {
    id: string;
    teamSlug: string;
    patchedJournalEntry?: Omit<PatchedJournalEntry, 'id'|'payee_name'|'total_debits'|'total_credits'|'is_balanced'|'created_at'|'updated_at'>;
}

export interface JournalEntriesRetrieveRequest {
    id: string;
    teamSlug: string;
}

export interface JournalEntriesUpdateRequest {
    id: string;
    teamSlug: string;
    journalEntry: Omit<JournalEntry, 'id'|'payee_name'|'total_debits'|'total_credits'|'is_balanced'|'created_at'|'updated_at'>;
}

export interface SimpleLinesCreateRequest {
    teamSlug: string;
    simpleLine: Omit<SimpleLine, 'line_id'|'journal_id'|'account_name'|'category_name'|'payee_name'|'source'|'status'|'created_at'|'updated_at'>;
}

export interface SimpleLinesDestroyRequest {
    id: string;
    teamSlug: string;
}

export interface SimpleLinesListRequest {
    teamSlug: string;
    account?: number;
    month?: string;
    page?: number;
}

export interface SimpleLinesPartialUpdateRequest {
    id: string;
    teamSlug: string;
    patchedSimpleLine?: Omit<PatchedSimpleLine, 'line_id'|'journal_id'|'account_name'|'category_name'|'payee_name'|'source'|'status'|'created_at'|'updated_at'>;
}

export interface SimpleLinesRecategorizeOperationRequest {
    id: string;
    teamSlug: string;
    simpleLinesRecategorizeRequest?: SimpleLinesRecategorizeRequest;
}

export interface SimpleLinesRetrieveRequest {
    id: string;
    teamSlug: string;
}

export interface SimpleLinesUpdateRequest {
    id: string;
    teamSlug: string;
    simpleLine: Omit<SimpleLine, 'line_id'|'journal_id'|'account_name'|'category_name'|'payee_name'|'source'|'status'|'created_at'|'updated_at'>;
}

/**
 * 
 */
export class JournalApi extends runtime.BaseAPI {

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesCreateRaw(requestParameters: JournalEntriesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JournalEntry>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesCreate().'
            );
        }

        if (requestParameters['journalEntry'] == null) {
            throw new runtime.RequiredError(
                'journalEntry',
                'Required parameter "journalEntry" was null or undefined when calling journalEntriesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JournalEntryToJSON(requestParameters['journalEntry']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesCreate(requestParameters: JournalEntriesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JournalEntry> {
        const response = await this.journalEntriesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesDestroyRaw(requestParameters: JournalEntriesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling journalEntriesDestroy().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesDestroy(requestParameters: JournalEntriesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.journalEntriesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesListRaw(requestParameters: JournalEntriesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedJournalEntryList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedJournalEntryListFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesList(requestParameters: JournalEntriesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedJournalEntryList> {
        const response = await this.journalEntriesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesPartialUpdateRaw(requestParameters: JournalEntriesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JournalEntry>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling journalEntriesPartialUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedJournalEntryToJSON(requestParameters['patchedJournalEntry']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesPartialUpdate(requestParameters: JournalEntriesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JournalEntry> {
        const response = await this.journalEntriesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesRetrieveRaw(requestParameters: JournalEntriesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JournalEntry>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling journalEntriesRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesRetrieve(requestParameters: JournalEntriesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JournalEntry> {
        const response = await this.journalEntriesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesUpdateRaw(requestParameters: JournalEntriesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JournalEntry>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling journalEntriesUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling journalEntriesUpdate().'
            );
        }

        if (requestParameters['journalEntry'] == null) {
            throw new runtime.RequiredError(
                'journalEntry',
                'Required parameter "journalEntry" was null or undefined when calling journalEntriesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/journal-entries/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: JournalEntryToJSON(requestParameters['journalEntry']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JournalEntryFromJSON(jsonValue));
    }

    /**
     * ViewSet for JournalEntry model. Provides CRUD operations for journal entries with nested lines.
     */
    async journalEntriesUpdate(requestParameters: JournalEntriesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JournalEntry> {
        const response = await this.journalEntriesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesCreateRaw(requestParameters: SimpleLinesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleLine>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleLinesCreate().'
            );
        }

        if (requestParameters['simpleLine'] == null) {
            throw new runtime.RequiredError(
                'simpleLine',
                'Required parameter "simpleLine" was null or undefined when calling simpleLinesCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/lines/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimpleLineToJSON(requestParameters['simpleLine']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleLineFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesCreate(requestParameters: SimpleLinesCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleLine> {
        const response = await this.simpleLinesCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesDestroyRaw(requestParameters: SimpleLinesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleLinesDestroy().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleLinesDestroy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/lines/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesDestroy(requestParameters: SimpleLinesDestroyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.simpleLinesDestroyRaw(requestParameters, initOverrides);
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesListRaw(requestParameters: SimpleLinesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedSimpleLineList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleLinesList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/lines/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedSimpleLineListFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesList(requestParameters: SimpleLinesListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedSimpleLineList> {
        const response = await this.simpleLinesListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesPartialUpdateRaw(requestParameters: SimpleLinesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleLine>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleLinesPartialUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleLinesPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/lines/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedSimpleLineToJSON(requestParameters['patchedSimpleLine']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleLineFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesPartialUpdate(requestParameters: SimpleLinesPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleLine> {
        const response = await this.simpleLinesPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Recategorize a journal line to a different account/category.  This changes the account on a single journal line, effectively moving the transaction to a different budget category.  POST body: {     \"new_category_id\": 456 }
     */
    async simpleLinesRecategorizeRaw(requestParameters: SimpleLinesRecategorizeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleLinesRecategorize200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleLinesRecategorize().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleLinesRecategorize().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/lines/{id}/recategorize/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SimpleLinesRecategorizeRequestToJSON(requestParameters['simpleLinesRecategorizeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleLinesRecategorize200ResponseFromJSON(jsonValue));
    }

    /**
     * Recategorize a journal line to a different account/category.  This changes the account on a single journal line, effectively moving the transaction to a different budget category.  POST body: {     \"new_category_id\": 456 }
     */
    async simpleLinesRecategorize(requestParameters: SimpleLinesRecategorizeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleLinesRecategorize200Response> {
        const response = await this.simpleLinesRecategorizeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesRetrieveRaw(requestParameters: SimpleLinesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleLine>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleLinesRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleLinesRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/lines/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleLineFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesRetrieve(requestParameters: SimpleLinesRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleLine> {
        const response = await this.simpleLinesRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesUpdateRaw(requestParameters: SimpleLinesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SimpleLine>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling simpleLinesUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling simpleLinesUpdate().'
            );
        }

        if (requestParameters['simpleLine'] == null) {
            throw new runtime.RequiredError(
                'simpleLine',
                'Required parameter "simpleLine" was null or undefined when calling simpleLinesUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/journal/api/lines/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SimpleLineToJSON(requestParameters['simpleLine']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SimpleLineFromJSON(jsonValue));
    }

    /**
     * ViewSet for simplified line interface. Provides CRUD operations for journal lines using a simple format that presents data from the line, parent journal entry, and sibling line.  This is designed for displaying transactions from the perspective of a single account, similar to a bank register view.  For create/update operations: - Creates/updates a journal entry with exactly 2 lines - The main line uses the specified account with inflow/outflow amounts - The sibling line uses the category account with opposite amounts  Query parameters for filtering: - account: Filter by account ID (useful for getting all transactions in a category) - month: Filter by month (YYYY-MM-DD format, uses first day of month)
     */
    async simpleLinesUpdate(requestParameters: SimpleLinesUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SimpleLine> {
        const response = await this.simpleLinesUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
