/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateLinkTokenResponse,
  ExchangePublicTokenRequest,
  ExchangePublicTokenResponse,
  ImportedTransaction,
  PaginatedImportedTransactionList,
  PaginatedPlaidAccountList,
  PaginatedPlaidItemList,
  PatchedPlaidAccount,
  PlaidAccount,
  PlaidItem,
  PlaidItemsSync200Response,
} from '../models/index';
import {
    CreateLinkTokenResponseFromJSON,
    CreateLinkTokenResponseToJSON,
    ExchangePublicTokenRequestFromJSON,
    ExchangePublicTokenRequestToJSON,
    ExchangePublicTokenResponseFromJSON,
    ExchangePublicTokenResponseToJSON,
    ImportedTransactionFromJSON,
    ImportedTransactionToJSON,
    PaginatedImportedTransactionListFromJSON,
    PaginatedImportedTransactionListToJSON,
    PaginatedPlaidAccountListFromJSON,
    PaginatedPlaidAccountListToJSON,
    PaginatedPlaidItemListFromJSON,
    PaginatedPlaidItemListToJSON,
    PatchedPlaidAccountFromJSON,
    PatchedPlaidAccountToJSON,
    PlaidAccountFromJSON,
    PlaidAccountToJSON,
    PlaidItemFromJSON,
    PlaidItemToJSON,
    PlaidItemsSync200ResponseFromJSON,
    PlaidItemsSync200ResponseToJSON,
} from '../models/index';

export interface BankFeedListRequest {
    account: number;
    teamSlug: string;
}

export interface ImportedTransactionsListRequest {
    teamSlug: string;
    page?: number;
}

export interface ImportedTransactionsRetrieveRequest {
    id: string;
    teamSlug: string;
}

export interface PlaidAccountsListRequest {
    teamSlug: string;
    page?: number;
}

export interface PlaidAccountsPartialUpdateRequest {
    id: number;
    teamSlug: string;
    patchedPlaidAccount?: Omit<PatchedPlaidAccount, 'id'|'item_details'|'account_details'|'created_at'|'updated_at'>;
}

export interface PlaidAccountsRetrieveRequest {
    id: number;
    teamSlug: string;
}

export interface PlaidCreateLinkTokenRequest {
    teamSlug: string;
}

export interface PlaidExchangePublicTokenRequest {
    teamSlug: string;
    exchangePublicTokenRequest: ExchangePublicTokenRequest;
}

export interface PlaidItemsListRequest {
    teamSlug: string;
    page?: number;
}

export interface PlaidItemsRetrieveRequest {
    id: number;
    teamSlug: string;
}

export interface PlaidItemsSyncRequest {
    id: number;
    teamSlug: string;
}

/**
 * 
 */
export class PlaidApi extends runtime.BaseAPI {

    /**
     * Get unified bank feed for an account. Query params: - account: Account ID to filter by (required)
     */
    async bankFeedListRaw(requestParameters: BankFeedListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['account'] == null) {
            throw new runtime.RequiredError(
                'account',
                'Required parameter "account" was null or undefined when calling bankFeedList().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling bankFeedList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/bank-feed/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get unified bank feed for an account. Query params: - account: Account ID to filter by (required)
     */
    async bankFeedList(requestParameters: BankFeedListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.bankFeedListRaw(requestParameters, initOverrides);
    }

    /**
     * ViewSet for ImportedTransaction model (read-only).
     */
    async importedTransactionsListRaw(requestParameters: ImportedTransactionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedImportedTransactionList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling importedTransactionsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/transactions/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedImportedTransactionListFromJSON(jsonValue));
    }

    /**
     * ViewSet for ImportedTransaction model (read-only).
     */
    async importedTransactionsList(requestParameters: ImportedTransactionsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedImportedTransactionList> {
        const response = await this.importedTransactionsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for ImportedTransaction model (read-only).
     */
    async importedTransactionsRetrieveRaw(requestParameters: ImportedTransactionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportedTransaction>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling importedTransactionsRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling importedTransactionsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/transactions/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportedTransactionFromJSON(jsonValue));
    }

    /**
     * ViewSet for ImportedTransaction model (read-only).
     */
    async importedTransactionsRetrieve(requestParameters: ImportedTransactionsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportedTransaction> {
        const response = await this.importedTransactionsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for PlaidAccount model. Allows updating the \'account\' field to map Plaid accounts to ledger accounts.
     */
    async plaidAccountsListRaw(requestParameters: PlaidAccountsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedPlaidAccountList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling plaidAccountsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/accounts/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedPlaidAccountListFromJSON(jsonValue));
    }

    /**
     * ViewSet for PlaidAccount model. Allows updating the \'account\' field to map Plaid accounts to ledger accounts.
     */
    async plaidAccountsList(requestParameters: PlaidAccountsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedPlaidAccountList> {
        const response = await this.plaidAccountsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for PlaidAccount model. Allows updating the \'account\' field to map Plaid accounts to ledger accounts.
     */
    async plaidAccountsPartialUpdateRaw(requestParameters: PlaidAccountsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaidAccount>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling plaidAccountsPartialUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling plaidAccountsPartialUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/accounts/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedPlaidAccountToJSON(requestParameters['patchedPlaidAccount']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaidAccountFromJSON(jsonValue));
    }

    /**
     * ViewSet for PlaidAccount model. Allows updating the \'account\' field to map Plaid accounts to ledger accounts.
     */
    async plaidAccountsPartialUpdate(requestParameters: PlaidAccountsPartialUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaidAccount> {
        const response = await this.plaidAccountsPartialUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for PlaidAccount model. Allows updating the \'account\' field to map Plaid accounts to ledger accounts.
     */
    async plaidAccountsRetrieveRaw(requestParameters: PlaidAccountsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaidAccount>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling plaidAccountsRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling plaidAccountsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/accounts/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaidAccountFromJSON(jsonValue));
    }

    /**
     * ViewSet for PlaidAccount model. Allows updating the \'account\' field to map Plaid accounts to ledger accounts.
     */
    async plaidAccountsRetrieve(requestParameters: PlaidAccountsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaidAccount> {
        const response = await this.plaidAccountsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a Plaid Link token for initializing Plaid Link. Returns a link_token that can be used to initialize Plaid Link in the frontend.
     */
    async plaidCreateLinkTokenRaw(requestParameters: PlaidCreateLinkTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateLinkTokenResponse>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling plaidCreateLinkToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/link-token/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateLinkTokenResponseFromJSON(jsonValue));
    }

    /**
     * Create a Plaid Link token for initializing Plaid Link. Returns a link_token that can be used to initialize Plaid Link in the frontend.
     */
    async plaidCreateLinkToken(requestParameters: PlaidCreateLinkTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateLinkTokenResponse> {
        const response = await this.plaidCreateLinkTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Exchange a public token for an access token and create PlaidItem and PlaidAccount records. Body: - public_token: Public token from Plaid Link - institution_id: Institution ID from Plaid Link - accounts: List of account objects from Plaid Link metadata
     */
    async plaidExchangePublicTokenRaw(requestParameters: PlaidExchangePublicTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExchangePublicTokenResponse>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling plaidExchangePublicToken().'
            );
        }

        if (requestParameters['exchangePublicTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'exchangePublicTokenRequest',
                'Required parameter "exchangePublicTokenRequest" was null or undefined when calling plaidExchangePublicToken().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/exchange-token/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ExchangePublicTokenRequestToJSON(requestParameters['exchangePublicTokenRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExchangePublicTokenResponseFromJSON(jsonValue));
    }

    /**
     * Exchange a public token for an access token and create PlaidItem and PlaidAccount records. Body: - public_token: Public token from Plaid Link - institution_id: Institution ID from Plaid Link - accounts: List of account objects from Plaid Link metadata
     */
    async plaidExchangePublicToken(requestParameters: PlaidExchangePublicTokenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExchangePublicTokenResponse> {
        const response = await this.plaidExchangePublicTokenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for PlaidItem model (read-only).
     */
    async plaidItemsListRaw(requestParameters: PlaidItemsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedPlaidItemList>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling plaidItemsList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/items/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedPlaidItemListFromJSON(jsonValue));
    }

    /**
     * ViewSet for PlaidItem model (read-only).
     */
    async plaidItemsList(requestParameters: PlaidItemsListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedPlaidItemList> {
        const response = await this.plaidItemsListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ViewSet for PlaidItem model (read-only).
     */
    async plaidItemsRetrieveRaw(requestParameters: PlaidItemsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaidItem>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling plaidItemsRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling plaidItemsRetrieve().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/items/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaidItemFromJSON(jsonValue));
    }

    /**
     * ViewSet for PlaidItem model (read-only).
     */
    async plaidItemsRetrieve(requestParameters: PlaidItemsRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaidItem> {
        const response = await this.plaidItemsRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Trigger transaction sync for this Plaid item. Starts a background Celery task to sync transactions from Plaid.  Validates that all accounts are mapped before syncing.
     */
    async plaidItemsSyncRaw(requestParameters: PlaidItemsSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PlaidItemsSync200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling plaidItemsSync().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling plaidItemsSync().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/plaid/api/items/{id}/sync/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlaidItemsSync200ResponseFromJSON(jsonValue));
    }

    /**
     * Trigger transaction sync for this Plaid item. Starts a background Celery task to sync transactions from Plaid.  Validates that all accounts are mapped before syncing.
     */
    async plaidItemsSync(requestParameters: PlaidItemsSyncRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PlaidItemsSync200Response> {
        const response = await this.plaidItemsSyncRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
