/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PatchedReconciliationUpdate,
  ReconciliationFinish,
  ReconciliationStart,
  ReconciliationTick,
  ReconciliationTickThrough,
} from '../models/index';
import {
    PatchedReconciliationUpdateFromJSON,
    PatchedReconciliationUpdateToJSON,
    ReconciliationFinishFromJSON,
    ReconciliationFinishToJSON,
    ReconciliationStartFromJSON,
    ReconciliationStartToJSON,
    ReconciliationTickFromJSON,
    ReconciliationTickToJSON,
    ReconciliationTickThroughFromJSON,
    ReconciliationTickThroughToJSON,
} from '../models/index';

export interface ReconciliationAccountsRequest {
    teamSlug: string;
}

export interface ReconciliationDiscardRequest {
    id: number;
    teamSlug: string;
}

export interface ReconciliationFinishRequest {
    id: number;
    teamSlug: string;
    reconciliationFinish?: ReconciliationFinish;
}

export interface ReconciliationListRequest {
    account: number;
    teamSlug: string;
}

export interface ReconciliationRetrieveRequest {
    id: number;
    teamSlug: string;
    includeLater?: boolean;
}

export interface ReconciliationStartRequest {
    teamSlug: string;
    reconciliationStart: ReconciliationStart;
}

export interface ReconciliationTickRequest {
    id: number;
    teamSlug: string;
    reconciliationTick: ReconciliationTick;
}

export interface ReconciliationTickThroughRequest {
    id: number;
    teamSlug: string;
    reconciliationTickThrough: ReconciliationTickThrough;
}

export interface ReconciliationUndoRequest {
    id: number;
    teamSlug: string;
}

export interface ReconciliationUntickAllRequest {
    id: number;
    teamSlug: string;
}

export interface ReconciliationUpdateRequest {
    id: number;
    teamSlug: string;
    patchedReconciliationUpdate?: PatchedReconciliationUpdate;
}

/**
 * 
 */
export class ReconciliationApi extends runtime.BaseAPI {

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationAccountsRaw(requestParameters: ReconciliationAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationAccounts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/accounts/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationAccounts(requestParameters: ReconciliationAccountsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationAccountsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationDiscardRaw(requestParameters: ReconciliationDiscardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reconciliationDiscard().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationDiscard().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationDiscard(requestParameters: ReconciliationDiscardRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reconciliationDiscardRaw(requestParameters, initOverrides);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationFinishRaw(requestParameters: ReconciliationFinishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reconciliationFinish().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationFinish().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/{id}/finish/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReconciliationFinishToJSON(requestParameters['reconciliationFinish']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationFinish(requestParameters: ReconciliationFinishRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationFinishRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationListRaw(requestParameters: ReconciliationListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['account'] == null) {
            throw new runtime.RequiredError(
                'account',
                'Required parameter "account" was null or undefined when calling reconciliationList().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['account'] != null) {
            queryParameters['account'] = requestParameters['account'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationList(requestParameters: ReconciliationListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationRetrieveRaw(requestParameters: ReconciliationRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reconciliationRetrieve().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationRetrieve().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeLater'] != null) {
            queryParameters['include_later'] = requestParameters['includeLater'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationRetrieve(requestParameters: ReconciliationRetrieveRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationRetrieveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationStartRaw(requestParameters: ReconciliationStartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationStart().'
            );
        }

        if (requestParameters['reconciliationStart'] == null) {
            throw new runtime.RequiredError(
                'reconciliationStart',
                'Required parameter "reconciliationStart" was null or undefined when calling reconciliationStart().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/`.replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReconciliationStartToJSON(requestParameters['reconciliationStart']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationStart(requestParameters: ReconciliationStartRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationStartRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationTickRaw(requestParameters: ReconciliationTickRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reconciliationTick().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationTick().'
            );
        }

        if (requestParameters['reconciliationTick'] == null) {
            throw new runtime.RequiredError(
                'reconciliationTick',
                'Required parameter "reconciliationTick" was null or undefined when calling reconciliationTick().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/{id}/tick/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReconciliationTickToJSON(requestParameters['reconciliationTick']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationTick(requestParameters: ReconciliationTickRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationTickRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationTickThroughRaw(requestParameters: ReconciliationTickThroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reconciliationTickThrough().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationTickThrough().'
            );
        }

        if (requestParameters['reconciliationTickThrough'] == null) {
            throw new runtime.RequiredError(
                'reconciliationTickThrough',
                'Required parameter "reconciliationTickThrough" was null or undefined when calling reconciliationTickThrough().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/{id}/tick_through/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReconciliationTickThroughToJSON(requestParameters['reconciliationTickThrough']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationTickThrough(requestParameters: ReconciliationTickThroughRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationTickThroughRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationUndoRaw(requestParameters: ReconciliationUndoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reconciliationUndo().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationUndo().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/{id}/undo/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationUndo(requestParameters: ReconciliationUndoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationUndoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationUntickAllRaw(requestParameters: ReconciliationUntickAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reconciliationUntickAll().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationUntickAll().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/{id}/untick_all/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationUntickAll(requestParameters: ReconciliationUntickAllRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationUntickAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationUpdateRaw(requestParameters: ReconciliationUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: any; }>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reconciliationUpdate().'
            );
        }

        if (requestParameters['teamSlug'] == null) {
            throw new runtime.RequiredError(
                'teamSlug',
                'Required parameter "teamSlug" was null or undefined when calling reconciliationUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // ApiKeyAuth authentication
        }

        const response = await this.request({
            path: `/a/{team_slug}/reconcile/api/reconciliations/{id}/`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"team_slug"}}`, encodeURIComponent(String(requestParameters['teamSlug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchedReconciliationUpdateToJSON(requestParameters['patchedReconciliationUpdate']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * /a/{team_slug}/reconcile/api/reconciliations/  Amounts in and out are in STATEMENT sign: what the paper statement prints.
     */
    async reconciliationUpdate(requestParameters: ReconciliationUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: any; }> {
        const response = await this.reconciliationUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
