# Generated by Django 6.0 on 2026-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus_employees', '0002_employee_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Date this item was archived', null=True),
        ),
    ]
