# Generated by Django 5.2.8 on 2025-12-17 18:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0004_invitation_is_archived_membership_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('entry_date', models.DateField(help_text='Date of the journal entry')),
                ('description', models.TextField(help_text='Description of the journal entry')),
                ('source', models.CharField(choices=[('manual', 'Manual Entry'), ('import', 'Import'), ('bank_match', 'Bank Match'), ('recurring', 'Recurring Entry')], default='manual', help_text='Source of this journal entry', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('void', 'Void')], default='draft', help_text='Status of the journal entry', max_length=20)),
                ('payee', models.ForeignKey(blank=True, help_text='Optional payee for this entry', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounts.payee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('dr_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Debit amount (sum of debits must equal sum of credits)', max_digits=15)),
                ('cr_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Credit amount (sum of credits must equal sum of debits)', max_digits=15)),
                ('is_cleared', models.BooleanField(default=False, help_text='Whether this line has cleared the bank')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether this line has been reconciled')),
                ('account', models.ForeignKey(help_text='The account being debited or credited', on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounts.account')),
                ('journal_entry', models.ForeignKey(help_text='The journal entry this line belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='journal.journalentry')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Journal Line',
                'verbose_name_plural': 'Journal Lines',
                'ordering': ['id'],
            },
        ),
    ]
