# Generated by Django 6.0 on 2026-09-23 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
        ("reconciliation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journalline",
            name="reconciliation",
            field=models.ForeignKey(
                blank=True,
                help_text="Statement this line was ticked or reconciled on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lines",
                to="reconciliation.reconciliation",
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual Entry"),
                    ("import", "Import"),
                    ("bank_match", "Bank Match"),
                    ("recurring", "Recurring Entry"),
                    ("reconciliation", "Reconciliation Adjustment"),
                ],
                default="manual",
                help_text="Source of this journal entry",
                max_length=20,
            ),
        ),
    ]
