# Generated by Django 6.0 on 2025-12-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='budget',
            field=models.ForeignKey(blank=True, editable=False, help_text='Link to budget based on account_id and journal entry date month', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='budget.budget'),
        ),
    ]
