# Generated by Django 6.0 on 2026-01-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journalline_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalline',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Whether this line has been archived'),
        ),
    ]
