# Generated by Django 6.0 on 2026-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_alter_journalline_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='reconciled_date',
            field=models.DateField(blank=True, help_text='Date this line was reconciled to a bank statement', null=True),
        ),
    ]
