# Generated by Django 5.2.8 on 2025-12-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0004_invitation_is_archived_membership_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('account_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('team', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.IntegerField(help_text='Account number (1000s for assets, 2000s for liabilities, etc.)')),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity')], max_length=20)),
                ('has_feed', models.BooleanField(default=False, help_text='Whether this account has a bank feed')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('account_group', models.ForeignKey(blank=True, help_text='Account group classification', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='transactions.accountgroup')),
            ],
            options={
                'ordering': ['account_number'],
                'unique_together': {('team', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('payee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('team', 'name')},
            },
        ),
    ]
