# Generated by Django 6.0 on 2026-09-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0005_invitation_archived_at_membership_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Set to true to archive this item"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="Date this item was archived", null=True
                    ),
                ),
                (
                    "answers",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw questionnaire answers, keyed by question id. Interpret against catalog_version.",
                    ),
                ),
                (
                    "catalog_version",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Version of the question catalog these answers were given against.",
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("questions", "Questions"),
                            ("review", "Chart of accounts review"),
                            ("tasks", "Guided tasks"),
                            ("done", "Done"),
                        ],
                        default="welcome",
                        max_length=20,
                    ),
                ),
                (
                    "question_phase",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Which questionnaire phase the user is on, while phase is 'questions'.",
                        max_length=20,
                    ),
                ),
                (
                    "tasks_done",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Slugs of guided tasks the user has completed or skipped.",
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "unique_together": {("team",)},
            },
        ),
    ]
