# Generated by Django 6.0 on 2026-09-23 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0008_add_sort_order"),
        ("teams", "0005_invitation_archived_at_membership_archived_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Set to true to archive this item"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="Date this item was archived", null=True
                    ),
                ),
                (
                    "statement_date",
                    models.DateField(help_text="Closing date printed on the statement"),
                ),
                (
                    "statement_balance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Closing balance on the statement, in ledger sign (dr - cr)",
                        max_digits=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("completed", "Completed"),
                            ("undone", "Undone"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "cleared_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "adjustment_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Adjustment posted at finish, ledger sign",
                        max_digits=15,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("undone_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        help_text="The asset or liability account this statement is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reconciliations",
                        to="accounts.account",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reconciliation",
                "verbose_name_plural": "Reconciliations",
                "ordering": ["-statement_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "draft")),
                        fields=("account",),
                        name="one_draft_reconciliation_per_account",
                    )
                ],
            },
        ),
    ]
