# Generated by Django 6.0 on 2026-07-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("user_login", "User Login"),
                    ("user_logout", "User Logout"),
                    ("login_failed", "Login Failed"),
                    ("csv_upload_started", "CSV Upload Started"),
                    ("csv_upload_completed", "CSV Upload Completed"),
                    ("csv_upload_failed", "CSV Upload Failed"),
                    ("plaid_sync_started", "Plaid Sync Started"),
                    ("plaid_sync_completed", "Plaid Sync Completed"),
                    ("plaid_sync_failed", "Plaid Sync Failed"),
                    ("bulk_categorize", "Bulk Categorize"),
                    ("bulk_edit", "Bulk Edit"),
                    ("bulk_reconcile", "Bulk Reconcile"),
                    ("bulk_unreconcile", "Bulk Unreconcile"),
                    ("bulk_archive", "Bulk Archive"),
                    ("bulk_unarchive", "Bulk Unarchive"),
                    ("bulk_delete", "Bulk Delete"),
                    ("bulk_duplicate", "Bulk Duplicate"),
                    ("transfer_dup_resolved", "Transfer Duplicate Resolved"),
                    ("transfer_dup_dismissed", "Transfer Duplicate Dismissed"),
                    ("team_member_added", "Team Member Added"),
                    ("team_member_removed", "Team Member Removed"),
                    ("goal_funds_assigned", "Goal Funds Assigned"),
                    ("goal_funds_withdrawn", "Goal Funds Withdrawn"),
                ],
                max_length=50,
            ),
        ),
    ]
