# Generated by Django 5.2.8 on 2025-12-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Set to true to archive this item'),
        ),
        migrations.AddField(
            model_name='membership',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Set to true to archive this item'),
        ),
        migrations.AddField(
            model_name='team',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Set to true to archive this item'),
        ),
    ]
