# Generated by Django 6.0 on 2026-01-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_invitation_is_archived_membership_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Date this item was archived', null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Date this item was archived', null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Date this item was archived', null=True),
        ),
    ]
