# Generated by Django 6.0 on 2026-09-18 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0005_invitation_archived_at_membership_archived_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyReviewState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Set to true to archive this item"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="Date this item was archived", null=True
                    ),
                ),
                (
                    "month",
                    models.DateField(help_text="First day of the reviewed month."),
                ),
                ("step", models.PositiveSmallIntegerField(default=0)),
                ("steps_seen", models.JSONField(blank=True, default=list)),
                ("baseline", models.CharField(default="3m", max_length=4)),
                ("notes", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teams.team",
                        verbose_name="Team",
                    ),
                ),
            ],
            options={
                "ordering": ["-month"],
                "unique_together": {("team", "month")},
            },
        ),
    ]
