/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountTypeEnum } from './AccountTypeEnum';
import {
    AccountTypeEnumFromJSON,
    AccountTypeEnumFromJSONTyped,
    AccountTypeEnumToJSON,
    AccountTypeEnumToJSONTyped,
} from './AccountTypeEnum';

/**
 * Serializer for AccountGroup model.
 * @export
 * @interface AccountGroup
 */
export interface AccountGroup {
    /**
     * 
     * @type {number}
     * @memberof AccountGroup
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof AccountGroup
     */
    name: string;
    /**
     * 
     * @type {AccountTypeEnum}
     * @memberof AccountGroup
     */
    accountType: AccountTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AccountGroup
     */
    description?: string;
    /**
     * 
     * @type {Date}
     * @memberof AccountGroup
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof AccountGroup
     */
    readonly updatedAt: Date;
    /**
     * Set to true to archive this item
     * @type {boolean}
     * @memberof AccountGroup
     */
    isArchived?: boolean;
    /**
     * Date this item was archived
     * @type {Date}
     * @memberof AccountGroup
     */
    readonly archivedAt: Date | null;
}



/**
 * Check if a given object implements the AccountGroup interface.
 */
export function instanceOfAccountGroup(value: object): value is AccountGroup {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('archivedAt' in value) || value['archivedAt'] === undefined) return false;
    return true;
}

export function AccountGroupFromJSON(json: any): AccountGroup {
    return AccountGroupFromJSONTyped(json, false);
}

export function AccountGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'accountType': AccountTypeEnumFromJSON(json['account_type']),
        'description': json['description'] == null ? undefined : json['description'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'isArchived': json['is_archived'] == null ? undefined : json['is_archived'],
        'archivedAt': (json['archived_at'] == null ? null : new Date(json['archived_at'])),
    };
}

  export function AccountGroupToJSON(json: any): AccountGroup {
      return AccountGroupToJSONTyped(json, false);
  }

  export function AccountGroupToJSONTyped(value?: Omit<AccountGroup, 'id'|'created_at'|'updated_at'|'archived_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'account_type': AccountTypeEnumToJSON(value['accountType']),
        'description': value['description'],
        'is_archived': value['isArchived'],
    };
}

