/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for Account model.
 * @export
 * @interface Account
 */
export interface Account {
    /**
     * 
     * @type {number}
     * @memberof Account
     */
    readonly accountId: number;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    name: string;
    /**
     * Account number (1000s for assets, 2000s for liabilities, etc.)
     * @type {number}
     * @memberof Account
     */
    accountNumber: number;
    /**
     * Account group classification
     * @type {number}
     * @memberof Account
     */
    accountGroup: number;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    readonly accountGroupName: string;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    readonly accountType: string;
    /**
     * Whether this account has a bank feed
     * @type {boolean}
     * @memberof Account
     */
    hasFeed?: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof Account
     */
    readonly journalLines: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof Account
     */
    readonly accountBalance: string;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof Account
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the Account interface.
 */
export function instanceOfAccount(value: object): value is Account {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    if (!('accountGroup' in value) || value['accountGroup'] === undefined) return false;
    if (!('accountGroupName' in value) || value['accountGroupName'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('journalLines' in value) || value['journalLines'] === undefined) return false;
    if (!('accountBalance' in value) || value['accountBalance'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function AccountFromJSON(json: any): Account {
    return AccountFromJSONTyped(json, false);
}

export function AccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): Account {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'name': json['name'],
        'accountNumber': json['account_number'],
        'accountGroup': json['account_group'],
        'accountGroupName': json['account_group_name'],
        'accountType': json['account_type'],
        'hasFeed': json['has_feed'] == null ? undefined : json['has_feed'],
        'journalLines': json['journal_lines'],
        'accountBalance': json['account_balance'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function AccountToJSON(json: any): Account {
      return AccountToJSONTyped(json, false);
  }

  export function AccountToJSONTyped(value?: Omit<Account, 'account_id'|'account_group_name'|'account_type'|'journal_lines'|'account_balance'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'account_number': value['accountNumber'],
        'account_group': value['accountGroup'],
        'has_feed': value['hasFeed'],
    };
}

