/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `CREATE` - Create
 * * `UPDATE` - Update
 * * `DELETE` - Delete
 * @export
 */
export const ActionEnum = {
    Create: 'CREATE',
    Update: 'UPDATE',
    Delete: 'DELETE'
} as const;
export type ActionEnum = typeof ActionEnum[keyof typeof ActionEnum];


export function instanceOfActionEnum(value: any): boolean {
    for (const key in ActionEnum) {
        if (Object.prototype.hasOwnProperty.call(ActionEnum, key)) {
            if (ActionEnum[key as keyof typeof ActionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ActionEnumFromJSON(json: any): ActionEnum {
    return ActionEnumFromJSONTyped(json, false);
}

export function ActionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ActionEnum {
    return json as ActionEnum;
}

export function ActionEnumToJSON(value?: ActionEnum | null): any {
    return value as any;
}

export function ActionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): ActionEnum {
    return value as ActionEnum;
}

