/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ActionEnum } from './ActionEnum';
import {
    ActionEnumFromJSON,
    ActionEnumFromJSONTyped,
    ActionEnumToJSON,
    ActionEnumToJSONTyped,
} from './ActionEnum';

/**
 * 
 * @export
 * @interface AuditLog
 */
export interface AuditLog {
    /**
     * 
     * @type {number}
     * @memberof AuditLog
     */
    readonly id: number;
    /**
     * 
     * @type {ActionEnum}
     * @memberof AuditLog
     */
    action: ActionEnum;
    /**
     * 
     * @type {string}
     * @memberof AuditLog
     */
    sourceModel?: string;
    /**
     * 
     * @type {Date}
     * @memberof AuditLog
     */
    readonly timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof AuditLog
     */
    readonly userDisplay: string;
    /**
     * 
     * @type {any}
     * @memberof AuditLog
     */
    changes?: any | null;
    /**
     * 
     * @type {number}
     * @memberof AuditLog
     */
    readonly eventId: number | null;
}



/**
 * Check if a given object implements the AuditLog interface.
 */
export function instanceOfAuditLog(value: object): value is AuditLog {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('action' in value) || value['action'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('userDisplay' in value) || value['userDisplay'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    return true;
}

export function AuditLogFromJSON(json: any): AuditLog {
    return AuditLogFromJSONTyped(json, false);
}

export function AuditLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuditLog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'action': ActionEnumFromJSON(json['action']),
        'sourceModel': json['source_model'] == null ? undefined : json['source_model'],
        'timestamp': (new Date(json['timestamp'])),
        'userDisplay': json['user_display'],
        'changes': json['changes'] == null ? undefined : json['changes'],
        'eventId': json['event_id'],
    };
}

  export function AuditLogToJSON(json: any): AuditLog {
      return AuditLogToJSONTyped(json, false);
  }

  export function AuditLogToJSONTyped(value?: Omit<AuditLog, 'id'|'timestamp'|'user_display'|'event_id'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'action': ActionEnumToJSON(value['action']),
        'source_model': value['sourceModel'],
        'changes': value['changes'],
    };
}

