/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleAccount } from './SimpleAccount';
import {
    SimpleAccountFromJSON,
    SimpleAccountFromJSONTyped,
    SimpleAccountToJSON,
    SimpleAccountToJSONTyped,
} from './SimpleAccount';
import type { BankFeedRowSourceEnum } from './BankFeedRowSourceEnum';
import {
    BankFeedRowSourceEnumFromJSON,
    BankFeedRowSourceEnumFromJSONTyped,
    BankFeedRowSourceEnumToJSON,
    BankFeedRowSourceEnumToJSONTyped,
} from './BankFeedRowSourceEnum';

/**
 * Unified bank feed row serializer.
 * This is NOT a model - it's a projection that combines data from
 * JournalLine (ledger) and BankTransaction (bank feed staging).
 * @export
 * @interface BankFeedRow
 */
export interface BankFeedRow {
    /**
     * Composite ID: 'ledger-{id}' or 'plaid-{id}'
     * @type {string}
     * @memberof BankFeedRow
     */
    id: string;
    /**
     * Source of this row
     * 
     * * `ledger` - ledger
     * * `plaid` - plaid
     * * `csv` - csv
     * * `system` - system
     * @type {BankFeedRowSourceEnum}
     * @memberof BankFeedRow
     */
    source: BankFeedRowSourceEnum;
    /**
     * Transaction date
     * @type {Date}
     * @memberof BankFeedRow
     */
    postedDate: Date;
    /**
     * Authorization date (Plaid only)
     * @type {Date}
     * @memberof BankFeedRow
     */
    authorizedDate: Date | null;
    /**
     * Transaction description
     * @type {string}
     * @memberof BankFeedRow
     */
    description: string;
    /**
     * Merchant name
     * @type {string}
     * @memberof BankFeedRow
     */
    merchantName: string | null;
    /**
     * The account this transaction affects
     * @type {SimpleAccount}
     * @memberof BankFeedRow
     */
    account: SimpleAccount;
    /**
     * Category account (null if uncategorized)
     * @type {SimpleAccount}
     * @memberof BankFeedRow
     */
    category: SimpleAccount | null;
    /**
     * Money coming in
     * @type {string}
     * @memberof BankFeedRow
     */
    inflow: string;
    /**
     * Money going out
     * @type {string}
     * @memberof BankFeedRow
     */
    outflow: string;
    /**
     * Whether transaction is pending
     * @type {boolean}
     * @memberof BankFeedRow
     */
    isPending: boolean;
    /**
     * Whether transaction is cleared
     * @type {boolean}
     * @memberof BankFeedRow
     */
    isCleared: boolean;
    /**
     * Whether transaction is archived
     * @type {boolean}
     * @memberof BankFeedRow
     */
    isArchived: boolean;
    /**
     * Whether transaction is reconciled
     * @type {boolean}
     * @memberof BankFeedRow
     */
    isReconciled: boolean;
    /**
     * Payee name (maps to merchant_name)
     * @type {string}
     * @memberof BankFeedRow
     */
    payee: string | null;
    /**
     * Payment channel (Plaid)
     * @type {string}
     * @memberof BankFeedRow
     */
    paymentChannel: string | null;
    /**
     * Categorization confidence
     * @type {string}
     * @memberof BankFeedRow
     */
    confidence: string | null;
    /**
     * ID of imported tx (if bank feed)
     * @type {number}
     * @memberof BankFeedRow
     */
    importedTransactionId: number | null;
    /**
     * Whether this row can be edited
     * @type {boolean}
     * @memberof BankFeedRow
     */
    isEditable: boolean;
}



/**
 * Check if a given object implements the BankFeedRow interface.
 */
export function instanceOfBankFeedRow(value: object): value is BankFeedRow {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('postedDate' in value) || value['postedDate'] === undefined) return false;
    if (!('authorizedDate' in value) || value['authorizedDate'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('merchantName' in value) || value['merchantName'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('inflow' in value) || value['inflow'] === undefined) return false;
    if (!('outflow' in value) || value['outflow'] === undefined) return false;
    if (!('isPending' in value) || value['isPending'] === undefined) return false;
    if (!('isCleared' in value) || value['isCleared'] === undefined) return false;
    if (!('isArchived' in value) || value['isArchived'] === undefined) return false;
    if (!('isReconciled' in value) || value['isReconciled'] === undefined) return false;
    if (!('payee' in value) || value['payee'] === undefined) return false;
    if (!('paymentChannel' in value) || value['paymentChannel'] === undefined) return false;
    if (!('confidence' in value) || value['confidence'] === undefined) return false;
    if (!('importedTransactionId' in value) || value['importedTransactionId'] === undefined) return false;
    if (!('isEditable' in value) || value['isEditable'] === undefined) return false;
    return true;
}

export function BankFeedRowFromJSON(json: any): BankFeedRow {
    return BankFeedRowFromJSONTyped(json, false);
}

export function BankFeedRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankFeedRow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'source': BankFeedRowSourceEnumFromJSON(json['source']),
        'postedDate': (new Date(json['posted_date'])),
        'authorizedDate': (json['authorized_date'] == null ? null : new Date(json['authorized_date'])),
        'description': json['description'],
        'merchantName': json['merchant_name'],
        'account': SimpleAccountFromJSON(json['account']),
        'category': SimpleAccountFromJSON(json['category']),
        'inflow': json['inflow'],
        'outflow': json['outflow'],
        'isPending': json['is_pending'],
        'isCleared': json['is_cleared'],
        'isArchived': json['is_archived'],
        'isReconciled': json['is_reconciled'],
        'payee': json['payee'],
        'paymentChannel': json['payment_channel'],
        'confidence': json['confidence'],
        'importedTransactionId': json['imported_transaction_id'],
        'isEditable': json['is_editable'],
    };
}

  export function BankFeedRowToJSON(json: any): BankFeedRow {
      return BankFeedRowToJSONTyped(json, false);
  }

  export function BankFeedRowToJSONTyped(value?: BankFeedRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'source': BankFeedRowSourceEnumToJSON(value['source']),
        'posted_date': ((value['postedDate']).toISOString().substring(0,10)),
        'authorized_date': (value['authorizedDate'] == null ? null : (value['authorizedDate'] as any).toISOString().substring(0,10)),
        'description': value['description'],
        'merchant_name': value['merchantName'],
        'account': SimpleAccountToJSON(value['account']),
        'category': SimpleAccountToJSON(value['category']),
        'inflow': value['inflow'],
        'outflow': value['outflow'],
        'is_pending': value['isPending'],
        'is_cleared': value['isCleared'],
        'is_archived': value['isArchived'],
        'is_reconciled': value['isReconciled'],
        'payee': value['payee'],
        'payment_channel': value['paymentChannel'],
        'confidence': value['confidence'],
        'imported_transaction_id': value['importedTransactionId'],
        'is_editable': value['isEditable'],
    };
}

