/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaidTransaction } from './PlaidTransaction';
import {
    PlaidTransactionFromJSON,
    PlaidTransactionFromJSONTyped,
    PlaidTransactionToJSON,
    PlaidTransactionToJSONTyped,
} from './PlaidTransaction';
import type { BankTransactionSourceEnum } from './BankTransactionSourceEnum';
import {
    BankTransactionSourceEnumFromJSON,
    BankTransactionSourceEnumFromJSONTyped,
    BankTransactionSourceEnumToJSON,
    BankTransactionSourceEnumToJSONTyped,
} from './BankTransactionSourceEnum';

/**
 * Serializer for BankTransaction model.
 * @export
 * @interface BankTransaction
 */
export interface BankTransaction {
    /**
     * 
     * @type {number}
     * @memberof BankTransaction
     */
    readonly id: number;
    /**
     * Source of this imported transaction (plaid, csv, manual)
     * 
     * * `plaid` - Plaid
     * * `csv` - CSV
     * * `manual` - Manual
     * * `system` - System
     * @type {BankTransactionSourceEnum}
     * @memberof BankTransaction
     */
    source?: BankTransactionSourceEnum;
    /**
     * Transaction amount (positive = outflow, negative = inflow in Plaid convention)
     * @type {string}
     * @memberof BankTransaction
     */
    amount: string;
    /**
     * The account this transaction belongs to
     * @type {number}
     * @memberof BankTransaction
     */
    account: number;
    /**
     * Transaction date
     * @type {Date}
     * @memberof BankTransaction
     */
    postedDate: Date;
    /**
     * 
     * @type {string}
     * @memberof BankTransaction
     */
    readonly pending: string;
    /**
     * Transaction description
     * @type {string}
     * @memberof BankTransaction
     */
    description: string;
    /**
     * Merchant name
     * @type {string}
     * @memberof BankTransaction
     */
    merchantName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BankTransaction
     */
    readonly plaidCategory: string;
    /**
     * 
     * @type {string}
     * @memberof BankTransaction
     */
    readonly plaidCategoryConfidence: string;
    /**
     * 
     * @type {string}
     * @memberof BankTransaction
     */
    readonly paymentChannel: string;
    /**
     * Journal entry created from this transaction (null = uncategorized)
     * @type {number}
     * @memberof BankTransaction
     */
    journalEntry?: number | null;
    /**
     * 
     * @type {boolean}
     * @memberof BankTransaction
     */
    readonly isCategorized: boolean;
    /**
     * 
     * @type {PlaidTransaction}
     * @memberof BankTransaction
     */
    readonly plaidTransaction: PlaidTransaction;
    /**
     * 
     * @type {Date}
     * @memberof BankTransaction
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof BankTransaction
     */
    readonly updatedAt: Date;
}



/**
 * Check if a given object implements the BankTransaction interface.
 */
export function instanceOfBankTransaction(value: object): value is BankTransaction {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('postedDate' in value) || value['postedDate'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('plaidCategory' in value) || value['plaidCategory'] === undefined) return false;
    if (!('plaidCategoryConfidence' in value) || value['plaidCategoryConfidence'] === undefined) return false;
    if (!('paymentChannel' in value) || value['paymentChannel'] === undefined) return false;
    if (!('isCategorized' in value) || value['isCategorized'] === undefined) return false;
    if (!('plaidTransaction' in value) || value['plaidTransaction'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function BankTransactionFromJSON(json: any): BankTransaction {
    return BankTransactionFromJSONTyped(json, false);
}

export function BankTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'source': json['source'] == null ? undefined : BankTransactionSourceEnumFromJSON(json['source']),
        'amount': json['amount'],
        'account': json['account'],
        'postedDate': (new Date(json['posted_date'])),
        'pending': json['pending'],
        'description': json['description'],
        'merchantName': json['merchant_name'] == null ? undefined : json['merchant_name'],
        'plaidCategory': json['plaid_category'],
        'plaidCategoryConfidence': json['plaid_category_confidence'],
        'paymentChannel': json['payment_channel'],
        'journalEntry': json['journal_entry'] == null ? undefined : json['journal_entry'],
        'isCategorized': json['is_categorized'],
        'plaidTransaction': PlaidTransactionFromJSON(json['plaid_transaction']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function BankTransactionToJSON(json: any): BankTransaction {
      return BankTransactionToJSONTyped(json, false);
  }

  export function BankTransactionToJSONTyped(value?: Omit<BankTransaction, 'id'|'pending'|'plaid_category'|'plaid_category_confidence'|'payment_channel'|'is_categorized'|'plaid_transaction'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'source': BankTransactionSourceEnumToJSON(value['source']),
        'amount': value['amount'],
        'account': value['account'],
        'posted_date': ((value['postedDate']).toISOString().substring(0,10)),
        'description': value['description'],
        'merchant_name': value['merchantName'],
        'journal_entry': value['journalEntry'],
    };
}

