/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `ledger` - ledger
 * * `plaid` - plaid
 * * `csv` - csv
 * * `system` - system
 * @export
 */
export const BankFeedRowSourceEnum = {
    Ledger: 'ledger',
    Plaid: 'plaid',
    Csv: 'csv',
    System: 'system'
} as const;
export type BankFeedRowSourceEnum = typeof BankFeedRowSourceEnum[keyof typeof BankFeedRowSourceEnum];


export function instanceOfBankFeedRowSourceEnum(value: any): boolean {
    for (const key in BankFeedRowSourceEnum) {
        if (Object.prototype.hasOwnProperty.call(BankFeedRowSourceEnum, key)) {
            if (BankFeedRowSourceEnum[key as keyof typeof BankFeedRowSourceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BankFeedRowSourceEnumFromJSON(json: any): BankFeedRowSourceEnum {
    return BankFeedRowSourceEnumFromJSONTyped(json, false);
}

export function BankFeedRowSourceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BankFeedRowSourceEnum {
    return json as BankFeedRowSourceEnum;
}

export function BankFeedRowSourceEnumToJSON(value?: BankFeedRowSourceEnum | null): any {
    return value as any;
}

export function BankFeedRowSourceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): BankFeedRowSourceEnum {
    return value as BankFeedRowSourceEnum;
}

