/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for batch categorize request.
 * @export
 * @interface BatchCategorizeRequest
 */
export interface BatchCategorizeRequest {
    /**
     * List of BankTransaction IDs to operate on
     * @type {Array<number>}
     * @memberof BatchCategorizeRequest
     */
    ids: Array<number>;
    /**
     * ID of the category account
     * @type {number}
     * @memberof BatchCategorizeRequest
     */
    categoryId: number;
}

/**
 * Check if a given object implements the BatchCategorizeRequest interface.
 */
export function instanceOfBatchCategorizeRequest(value: object): value is BatchCategorizeRequest {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    return true;
}

export function BatchCategorizeRequestFromJSON(json: any): BatchCategorizeRequest {
    return BatchCategorizeRequestFromJSONTyped(json, false);
}

export function BatchCategorizeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchCategorizeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
        'categoryId': json['category_id'],
    };
}

  export function BatchCategorizeRequestToJSON(json: any): BatchCategorizeRequest {
      return BatchCategorizeRequestToJSONTyped(json, false);
  }

  export function BatchCategorizeRequestToJSONTyped(value?: BatchCategorizeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
        'category_id': value['categoryId'],
    };
}

