/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for batch reconcile request.
 * @export
 * @interface BatchReconcileRequest
 */
export interface BatchReconcileRequest {
    /**
     * List of BankTransaction IDs to operate on
     * @type {Array<number>}
     * @memberof BatchReconcileRequest
     */
    ids: Array<number>;
    /**
     * Optional adjustment amount to create if balance doesn't match
     * @type {string}
     * @memberof BatchReconcileRequest
     */
    adjustmentAmount?: string;
}

/**
 * Check if a given object implements the BatchReconcileRequest interface.
 */
export function instanceOfBatchReconcileRequest(value: object): value is BatchReconcileRequest {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function BatchReconcileRequestFromJSON(json: any): BatchReconcileRequest {
    return BatchReconcileRequestFromJSONTyped(json, false);
}

export function BatchReconcileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchReconcileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
        'adjustmentAmount': json['adjustment_amount'] == null ? undefined : json['adjustment_amount'],
    };
}

  export function BatchReconcileRequestToJSON(json: any): BatchReconcileRequest {
      return BatchReconcileRequestToJSONTyped(json, false);
  }

  export function BatchReconcileRequestToJSONTyped(value?: BatchReconcileRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
        'adjustment_amount': value['adjustmentAmount'],
    };
}

