/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for batch set payee request.
 * @export
 * @interface BatchSetPayeeRequest
 */
export interface BatchSetPayeeRequest {
    /**
     * List of BankTransaction IDs to operate on
     * @type {Array<number>}
     * @memberof BatchSetPayeeRequest
     */
    ids: Array<number>;
    /**
     * Payee/merchant name
     * @type {string}
     * @memberof BatchSetPayeeRequest
     */
    payee: string;
}

/**
 * Check if a given object implements the BatchSetPayeeRequest interface.
 */
export function instanceOfBatchSetPayeeRequest(value: object): value is BatchSetPayeeRequest {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    if (!('payee' in value) || value['payee'] === undefined) return false;
    return true;
}

export function BatchSetPayeeRequestFromJSON(json: any): BatchSetPayeeRequest {
    return BatchSetPayeeRequestFromJSONTyped(json, false);
}

export function BatchSetPayeeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): BatchSetPayeeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
        'payee': json['payee'],
    };
}

  export function BatchSetPayeeRequestToJSON(json: any): BatchSetPayeeRequest {
      return BatchSetPayeeRequestToJSONTyped(json, false);
  }

  export function BatchSetPayeeRequestToJSONTyped(value?: BatchSetPayeeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
        'payee': value['payee'],
    };
}

