/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionRow } from './TransactionRow';
import {
    TransactionRowFromJSON,
    TransactionRowFromJSONTyped,
    TransactionRowToJSON,
    TransactionRowToJSONTyped,
} from './TransactionRow';

/**
 * Serializer for categorize transactions request body.
 * @export
 * @interface CategorizeTransactionsRequest
 */
export interface CategorizeTransactionsRequest {
    /**
     * List of transactions to categorize
     * @type {Array<TransactionRow>}
     * @memberof CategorizeTransactionsRequest
     */
    rows: Array<TransactionRow>;
    /**
     * ID of the category account
     * @type {number}
     * @memberof CategorizeTransactionsRequest
     */
    categoryId: number;
}

/**
 * Check if a given object implements the CategorizeTransactionsRequest interface.
 */
export function instanceOfCategorizeTransactionsRequest(value: object): value is CategorizeTransactionsRequest {
    if (!('rows' in value) || value['rows'] === undefined) return false;
    if (!('categoryId' in value) || value['categoryId'] === undefined) return false;
    return true;
}

export function CategorizeTransactionsRequestFromJSON(json: any): CategorizeTransactionsRequest {
    return CategorizeTransactionsRequestFromJSONTyped(json, false);
}

export function CategorizeTransactionsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategorizeTransactionsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'rows': ((json['rows'] as Array<any>).map(TransactionRowFromJSON)),
        'categoryId': json['category_id'],
    };
}

  export function CategorizeTransactionsRequestToJSON(json: any): CategorizeTransactionsRequest {
      return CategorizeTransactionsRequestToJSONTyped(json, false);
  }

  export function CategorizeTransactionsRequestToJSONTyped(value?: CategorizeTransactionsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rows': ((value['rows'] as Array<any>).map(TransactionRowToJSON)),
        'category_id': value['categoryId'],
    };
}

