/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLinkTokenResponse
 */
export interface CreateLinkTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateLinkTokenResponse
     */
    linkToken: string;
}

/**
 * Check if a given object implements the CreateLinkTokenResponse interface.
 */
export function instanceOfCreateLinkTokenResponse(value: object): value is CreateLinkTokenResponse {
    if (!('linkToken' in value) || value['linkToken'] === undefined) return false;
    return true;
}

export function CreateLinkTokenResponseFromJSON(json: any): CreateLinkTokenResponse {
    return CreateLinkTokenResponseFromJSONTyped(json, false);
}

export function CreateLinkTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLinkTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'linkToken': json['link_token'],
    };
}

  export function CreateLinkTokenResponseToJSON(json: any): CreateLinkTokenResponse {
      return CreateLinkTokenResponseToJSONTyped(json, false);
  }

  export function CreateLinkTokenResponseToJSONTyped(value?: CreateLinkTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'link_token': value['linkToken'],
    };
}

