/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangePublicTokenResponse
 */
export interface ExchangePublicTokenResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ExchangePublicTokenResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the ExchangePublicTokenResponse interface.
 */
export function instanceOfExchangePublicTokenResponse(value: object): value is ExchangePublicTokenResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function ExchangePublicTokenResponseFromJSON(json: any): ExchangePublicTokenResponse {
    return ExchangePublicTokenResponseFromJSONTyped(json, false);
}

export function ExchangePublicTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangePublicTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

  export function ExchangePublicTokenResponseToJSON(json: any): ExchangePublicTokenResponse {
      return ExchangePublicTokenResponseToJSONTyped(json, false);
  }

  export function ExchangePublicTokenResponseToJSONTyped(value?: ExchangePublicTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
    };
}

