/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExchangePublicTokenRequest
 */
export interface ExchangePublicTokenRequest {
    /**
     * 
     * @type {string}
     * @memberof ExchangePublicTokenRequest
     */
    publicToken: string;
    /**
     * 
     * @type {string}
     * @memberof ExchangePublicTokenRequest
     */
    institutionId: string;
    /**
     * 
     * @type {Array<{ [key: string]: any; }>}
     * @memberof ExchangePublicTokenRequest
     */
    accounts?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the ExchangePublicTokenRequest interface.
 */
export function instanceOfExchangePublicTokenRequest(value: object): value is ExchangePublicTokenRequest {
    if (!('publicToken' in value) || value['publicToken'] === undefined) return false;
    if (!('institutionId' in value) || value['institutionId'] === undefined) return false;
    return true;
}

export function ExchangePublicTokenRequestFromJSON(json: any): ExchangePublicTokenRequest {
    return ExchangePublicTokenRequestFromJSONTyped(json, false);
}

export function ExchangePublicTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExchangePublicTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'publicToken': json['public_token'],
        'institutionId': json['institution_id'],
        'accounts': json['accounts'] == null ? undefined : json['accounts'],
    };
}

  export function ExchangePublicTokenRequestToJSON(json: any): ExchangePublicTokenRequest {
      return ExchangePublicTokenRequestToJSONTyped(json, false);
  }

  export function ExchangePublicTokenRequestToJSONTyped(value?: ExchangePublicTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'public_token': value['publicToken'],
        'institution_id': value['institutionId'],
        'accounts': value['accounts'],
    };
}

