/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * AccountSerializer plus the count of transactions awaiting categorization, for the account picker.
 * @export
 * @interface FeedAccount
 */
export interface FeedAccount {
    /**
     * 
     * @type {number}
     * @memberof FeedAccount
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof FeedAccount
     */
    name: string;
    /**
     * Account group classification
     * @type {number}
     * @memberof FeedAccount
     */
    accountGroup: number;
    /**
     * 
     * @type {string}
     * @memberof FeedAccount
     */
    readonly accountGroupName: string;
    /**
     * 
     * @type {string}
     * @memberof FeedAccount
     */
    readonly accountType: string;
    /**
     * Bank or financial institution this account is held with
     * @type {number}
     * @memberof FeedAccount
     */
    institution?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FeedAccount
     */
    readonly institutionName: string;
    /**
     * Whether this account has a bank feed
     * @type {boolean}
     * @memberof FeedAccount
     */
    hasFeed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof FeedAccount
     */
    readonly balance: string;
    /**
     * Same as `balance` now that archived entries count nowhere; kept for API compatibility.
     * @type {string}
     * @memberof FeedAccount
     */
    readonly categorizedBalance: string | null;
    /**
     * Get reconciled_balance from annotation if available.
     * @type {string}
     * @memberof FeedAccount
     */
    readonly reconciledBalance: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FeedAccount
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof FeedAccount
     */
    readonly updatedAt: Date;
    /**
     * Set to true to archive this item
     * @type {boolean}
     * @memberof FeedAccount
     */
    isArchived?: boolean;
    /**
     * Date this item was archived
     * @type {Date}
     * @memberof FeedAccount
     */
    readonly archivedAt: Date | null;
    /**
     * 
     * @type {number}
     * @memberof FeedAccount
     */
    readonly uncategorizedCount: number;
    /**
     * 
     * @type {Date}
     * @memberof FeedAccount
     */
    readonly latestTransactionDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof FeedAccount
     */
    readonly latestReconciledDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof FeedAccount
     */
    readonly lastStatementDate: Date;
    /**
     * 
     * @type {boolean}
     * @memberof FeedAccount
     */
    readonly lastStatementIntact: boolean | null;
}

/**
 * Check if a given object implements the FeedAccount interface.
 */
export function instanceOfFeedAccount(value: object): value is FeedAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('accountGroup' in value) || value['accountGroup'] === undefined) return false;
    if (!('accountGroupName' in value) || value['accountGroupName'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('institutionName' in value) || value['institutionName'] === undefined) return false;
    if (!('balance' in value) || value['balance'] === undefined) return false;
    if (!('categorizedBalance' in value) || value['categorizedBalance'] === undefined) return false;
    if (!('reconciledBalance' in value) || value['reconciledBalance'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('archivedAt' in value) || value['archivedAt'] === undefined) return false;
    if (!('uncategorizedCount' in value) || value['uncategorizedCount'] === undefined) return false;
    if (!('latestTransactionDate' in value) || value['latestTransactionDate'] === undefined) return false;
    if (!('latestReconciledDate' in value) || value['latestReconciledDate'] === undefined) return false;
    if (!('lastStatementDate' in value) || value['lastStatementDate'] === undefined) return false;
    if (!('lastStatementIntact' in value) || value['lastStatementIntact'] === undefined) return false;
    return true;
}

export function FeedAccountFromJSON(json: any): FeedAccount {
    return FeedAccountFromJSONTyped(json, false);
}

export function FeedAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeedAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'accountGroup': json['account_group'],
        'accountGroupName': json['account_group_name'],
        'accountType': json['account_type'],
        'institution': json['institution'] == null ? undefined : json['institution'],
        'institutionName': json['institution_name'],
        'hasFeed': json['has_feed'] == null ? undefined : json['has_feed'],
        'balance': json['balance'],
        'categorizedBalance': json['categorized_balance'],
        'reconciledBalance': json['reconciled_balance'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
        'isArchived': json['is_archived'] == null ? undefined : json['is_archived'],
        'archivedAt': (json['archived_at'] == null ? null : new Date(json['archived_at'])),
        'uncategorizedCount': json['uncategorized_count'],
        'latestTransactionDate': (new Date(json['latest_transaction_date'])),
        'latestReconciledDate': (new Date(json['latest_reconciled_date'])),
        'lastStatementDate': (new Date(json['last_statement_date'])),
        'lastStatementIntact': json['last_statement_intact'],
    };
}

  export function FeedAccountToJSON(json: any): FeedAccount {
      return FeedAccountToJSONTyped(json, false);
  }

  export function FeedAccountToJSONTyped(value?: Omit<FeedAccount, 'id'|'account_group_name'|'account_type'|'institution_name'|'balance'|'categorized_balance'|'reconciled_balance'|'created_at'|'updated_at'|'archived_at'|'uncategorized_count'|'latest_transaction_date'|'latest_reconciled_date'|'last_statement_date'|'last_statement_intact'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'account_group': value['accountGroup'],
        'institution': value['institution'],
        'has_feed': value['hasFeed'],
        'is_archived': value['isArchived'],
    };
}

