/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `draft` - Draft
 * * `posted` - Posted
 * * `void` - Void
 * @export
 */
export const JournalEntryStatusEnum = {
    Draft: 'draft',
    Posted: 'posted',
    Void: 'void'
} as const;
export type JournalEntryStatusEnum = typeof JournalEntryStatusEnum[keyof typeof JournalEntryStatusEnum];


export function instanceOfJournalEntryStatusEnum(value: any): boolean {
    for (const key in JournalEntryStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(JournalEntryStatusEnum, key)) {
            if (JournalEntryStatusEnum[key as keyof typeof JournalEntryStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JournalEntryStatusEnumFromJSON(json: any): JournalEntryStatusEnum {
    return JournalEntryStatusEnumFromJSONTyped(json, false);
}

export function JournalEntryStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalEntryStatusEnum {
    return json as JournalEntryStatusEnum;
}

export function JournalEntryStatusEnumToJSON(value?: JournalEntryStatusEnum | null): any {
    return value as any;
}

export function JournalEntryStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): JournalEntryStatusEnum {
    return value as JournalEntryStatusEnum;
}

