/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for JournalLine model with nested account details.
 * @export
 * @interface JournalLine
 */
export interface JournalLine {
    /**
     * 
     * @type {number}
     * @memberof JournalLine
     */
    readonly id: number;
    /**
     * The account being debited or credited
     * @type {number}
     * @memberof JournalLine
     */
    account: number;
    /**
     * 
     * @type {string}
     * @memberof JournalLine
     */
    readonly accountName: string;
    /**
     * 
     * @type {number}
     * @memberof JournalLine
     */
    readonly accountNumber: number;
    /**
     * Debit amount (sum of debits must equal sum of credits)
     * @type {string}
     * @memberof JournalLine
     */
    drAmount?: string;
    /**
     * Credit amount (sum of credits must equal sum of debits)
     * @type {string}
     * @memberof JournalLine
     */
    crAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof JournalLine
     */
    readonly amount: string;
    /**
     * Whether this line has cleared the bank
     * @type {boolean}
     * @memberof JournalLine
     */
    isCleared?: boolean;
    /**
     * Whether this line has been reconciled
     * @type {boolean}
     * @memberof JournalLine
     */
    isReconciled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof JournalLine
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof JournalLine
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the JournalLine interface.
 */
export function instanceOfJournalLine(value: object): value is JournalLine {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function JournalLineFromJSON(json: any): JournalLine {
    return JournalLineFromJSONTyped(json, false);
}

export function JournalLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalLine {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'account': json['account'],
        'accountName': json['account_name'],
        'accountNumber': json['account_number'],
        'drAmount': json['dr_amount'] == null ? undefined : json['dr_amount'],
        'crAmount': json['cr_amount'] == null ? undefined : json['cr_amount'],
        'amount': json['amount'],
        'isCleared': json['is_cleared'] == null ? undefined : json['is_cleared'],
        'isReconciled': json['is_reconciled'] == null ? undefined : json['is_reconciled'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function JournalLineToJSON(json: any): JournalLine {
      return JournalLineToJSONTyped(json, false);
  }

  export function JournalLineToJSONTyped(value?: Omit<JournalLine, 'id'|'account_name'|'account_number'|'amount'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'dr_amount': value['drAmount'],
        'cr_amount': value['crAmount'],
        'is_cleared': value['isCleared'],
        'is_reconciled': value['isReconciled'],
    };
}

