/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JournalLine } from './JournalLine';
import {
    JournalLineFromJSON,
    JournalLineFromJSONTyped,
    JournalLineToJSON,
    JournalLineToJSONTyped,
} from './JournalLine';
import type { JournalEntryStatusEnum } from './JournalEntryStatusEnum';
import {
    JournalEntryStatusEnumFromJSON,
    JournalEntryStatusEnumFromJSONTyped,
    JournalEntryStatusEnumToJSON,
    JournalEntryStatusEnumToJSONTyped,
} from './JournalEntryStatusEnum';
import type { SourceEnum } from './SourceEnum';
import {
    SourceEnumFromJSON,
    SourceEnumFromJSONTyped,
    SourceEnumToJSON,
    SourceEnumToJSONTyped,
} from './SourceEnum';

/**
 * Serializer for JournalEntry model with nested lines.
 * Supports creating/updating journal entries with lines in a single request.
 * @export
 * @interface JournalEntry
 */
export interface JournalEntry {
    /**
     * 
     * @type {number}
     * @memberof JournalEntry
     */
    readonly id: number;
    /**
     * Date of the journal entry
     * @type {Date}
     * @memberof JournalEntry
     */
    entryDate: Date;
    /**
     * Optional payee for this entry
     * @type {number}
     * @memberof JournalEntry
     */
    payee?: number | null;
    /**
     * 
     * @type {string}
     * @memberof JournalEntry
     */
    readonly payeeName: string | null;
    /**
     * Description of the journal entry
     * @type {string}
     * @memberof JournalEntry
     */
    description: string;
    /**
     * Source of this journal entry
     * 
     * * `manual` - Manual Entry
     * * `import` - Import
     * * `bank_match` - Bank Match
     * * `recurring` - Recurring Entry
     * @type {SourceEnum}
     * @memberof JournalEntry
     */
    source?: SourceEnum;
    /**
     * Status of the journal entry
     * 
     * * `draft` - Draft
     * * `posted` - Posted
     * * `void` - Void
     * @type {JournalEntryStatusEnum}
     * @memberof JournalEntry
     */
    status?: JournalEntryStatusEnum;
    /**
     * 
     * @type {Array<JournalLine>}
     * @memberof JournalEntry
     */
    lines: Array<JournalLine>;
    /**
     * 
     * @type {string}
     * @memberof JournalEntry
     */
    readonly totalDebits: string;
    /**
     * 
     * @type {string}
     * @memberof JournalEntry
     */
    readonly totalCredits: string;
    /**
     * 
     * @type {boolean}
     * @memberof JournalEntry
     */
    readonly isBalanced: boolean;
    /**
     * 
     * @type {Date}
     * @memberof JournalEntry
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof JournalEntry
     */
    readonly updatedAt: Date;
}



/**
 * Check if a given object implements the JournalEntry interface.
 */
export function instanceOfJournalEntry(value: object): value is JournalEntry {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('entryDate' in value) || value['entryDate'] === undefined) return false;
    if (!('payeeName' in value) || value['payeeName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('lines' in value) || value['lines'] === undefined) return false;
    if (!('totalDebits' in value) || value['totalDebits'] === undefined) return false;
    if (!('totalCredits' in value) || value['totalCredits'] === undefined) return false;
    if (!('isBalanced' in value) || value['isBalanced'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function JournalEntryFromJSON(json: any): JournalEntry {
    return JournalEntryFromJSONTyped(json, false);
}

export function JournalEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'entryDate': (new Date(json['entry_date'])),
        'payee': json['payee'] == null ? undefined : json['payee'],
        'payeeName': json['payee_name'],
        'description': json['description'],
        'source': json['source'] == null ? undefined : SourceEnumFromJSON(json['source']),
        'status': json['status'] == null ? undefined : JournalEntryStatusEnumFromJSON(json['status']),
        'lines': ((json['lines'] as Array<any>).map(JournalLineFromJSON)),
        'totalDebits': json['total_debits'],
        'totalCredits': json['total_credits'],
        'isBalanced': json['is_balanced'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function JournalEntryToJSON(json: any): JournalEntry {
      return JournalEntryToJSONTyped(json, false);
  }

  export function JournalEntryToJSONTyped(value?: Omit<JournalEntry, 'id'|'payee_name'|'total_debits'|'total_credits'|'is_balanced'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'entry_date': ((value['entryDate']).toISOString().substring(0,10)),
        'payee': value['payee'],
        'description': value['description'],
        'source': SourceEnumToJSON(value['source']),
        'status': JournalEntryStatusEnumToJSON(value['status']),
        'lines': ((value['lines'] as Array<any>).map(JournalLineToJSON)),
    };
}

