/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `manual` - Manual Entry
 * * `import` - Import
 * * `bank_match` - Bank Match
 * * `recurring` - Recurring Entry
 * @export
 */
export const JournalEntrySourceEnum = {
    Manual: 'manual',
    Import: 'import',
    BankMatch: 'bank_match',
    Recurring: 'recurring'
} as const;
export type JournalEntrySourceEnum = typeof JournalEntrySourceEnum[keyof typeof JournalEntrySourceEnum];


export function instanceOfJournalEntrySourceEnum(value: any): boolean {
    for (const key in JournalEntrySourceEnum) {
        if (Object.prototype.hasOwnProperty.call(JournalEntrySourceEnum, key)) {
            if (JournalEntrySourceEnum[key as keyof typeof JournalEntrySourceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JournalEntrySourceEnumFromJSON(json: any): JournalEntrySourceEnum {
    return JournalEntrySourceEnumFromJSONTyped(json, false);
}

export function JournalEntrySourceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalEntrySourceEnum {
    return json as JournalEntrySourceEnum;
}

export function JournalEntrySourceEnumToJSON(value?: JournalEntrySourceEnum | null): any {
    return value as any;
}

export function JournalEntrySourceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): JournalEntrySourceEnum {
    return value as JournalEntrySourceEnum;
}

