/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `payee` - payee
 * * `description` - description
 * * `similar` - similar
 * @export
 */
export const MatchTypeEnum = {
    Payee: 'payee',
    Description: 'description',
    Similar: 'similar'
} as const;
export type MatchTypeEnum = typeof MatchTypeEnum[keyof typeof MatchTypeEnum];


export function instanceOfMatchTypeEnum(value: any): boolean {
    for (const key in MatchTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(MatchTypeEnum, key)) {
            if (MatchTypeEnum[key as keyof typeof MatchTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MatchTypeEnumFromJSON(json: any): MatchTypeEnum {
    return MatchTypeEnumFromJSONTyped(json, false);
}

export function MatchTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): MatchTypeEnum {
    return json as MatchTypeEnum;
}

export function MatchTypeEnumToJSON(value?: MatchTypeEnum | null): any {
    return value as any;
}

export function MatchTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): MatchTypeEnum {
    return value as MatchTypeEnum;
}

