/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JournalEntry } from './JournalEntry';
import {
    JournalEntryFromJSON,
    JournalEntryFromJSONTyped,
    JournalEntryToJSON,
    JournalEntryToJSONTyped,
} from './JournalEntry';

/**
 * 
 * @export
 * @interface PaginatedJournalEntryList
 */
export interface PaginatedJournalEntryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedJournalEntryList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedJournalEntryList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedJournalEntryList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<JournalEntry>}
     * @memberof PaginatedJournalEntryList
     */
    results: Array<JournalEntry>;
}

/**
 * Check if a given object implements the PaginatedJournalEntryList interface.
 */
export function instanceOfPaginatedJournalEntryList(value: object): value is PaginatedJournalEntryList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedJournalEntryListFromJSON(json: any): PaginatedJournalEntryList {
    return PaginatedJournalEntryListFromJSONTyped(json, false);
}

export function PaginatedJournalEntryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedJournalEntryList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(JournalEntryFromJSON)),
    };
}

  export function PaginatedJournalEntryListToJSON(json: any): PaginatedJournalEntryList {
      return PaginatedJournalEntryListToJSONTyped(json, false);
  }

  export function PaginatedJournalEntryListToJSONTyped(value?: PaginatedJournalEntryList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(JournalEntryToJSON)),
    };
}

