/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditLog } from './AuditLog';
import {
    AuditLogFromJSON,
    AuditLogFromJSONTyped,
    AuditLogToJSON,
    AuditLogToJSONTyped,
} from './AuditLog';

/**
 * 
 * @export
 * @interface PaginatedAuditLogList
 */
export interface PaginatedAuditLogList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAuditLogList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAuditLogList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAuditLogList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AuditLog>}
     * @memberof PaginatedAuditLogList
     */
    results: Array<AuditLog>;
}

/**
 * Check if a given object implements the PaginatedAuditLogList interface.
 */
export function instanceOfPaginatedAuditLogList(value: object): value is PaginatedAuditLogList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAuditLogListFromJSON(json: any): PaginatedAuditLogList {
    return PaginatedAuditLogListFromJSONTyped(json, false);
}

export function PaginatedAuditLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAuditLogList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AuditLogFromJSON)),
    };
}

  export function PaginatedAuditLogListToJSON(json: any): PaginatedAuditLogList {
      return PaginatedAuditLogListToJSONTyped(json, false);
  }

  export function PaginatedAuditLogListToJSONTyped(value?: PaginatedAuditLogList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AuditLogToJSON)),
    };
}

