/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionRow } from './TransactionRow';
import {
    TransactionRowFromJSON,
    TransactionRowFromJSONTyped,
    TransactionRowToJSON,
    TransactionRowToJSONTyped,
} from './TransactionRow';

/**
 * 
 * @export
 * @interface PaginatedTransactionRowList
 */
export interface PaginatedTransactionRowList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedTransactionRowList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTransactionRowList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedTransactionRowList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<TransactionRow>}
     * @memberof PaginatedTransactionRowList
     */
    results: Array<TransactionRow>;
}

/**
 * Check if a given object implements the PaginatedTransactionRowList interface.
 */
export function instanceOfPaginatedTransactionRowList(value: object): value is PaginatedTransactionRowList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedTransactionRowListFromJSON(json: any): PaginatedTransactionRowList {
    return PaginatedTransactionRowListFromJSONTyped(json, false);
}

export function PaginatedTransactionRowListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTransactionRowList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(TransactionRowFromJSON)),
    };
}

  export function PaginatedTransactionRowListToJSON(json: any): PaginatedTransactionRowList {
      return PaginatedTransactionRowListToJSONTyped(json, false);
  }

  export function PaginatedTransactionRowListToJSONTyped(value?: PaginatedTransactionRowList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(TransactionRowToJSON)),
    };
}

