/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaidItem } from './PlaidItem';
import {
    PlaidItemFromJSON,
    PlaidItemFromJSONTyped,
    PlaidItemToJSON,
    PlaidItemToJSONTyped,
} from './PlaidItem';

/**
 * 
 * @export
 * @interface PaginatedPlaidItemList
 */
export interface PaginatedPlaidItemList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPlaidItemList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlaidItemList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlaidItemList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PlaidItem>}
     * @memberof PaginatedPlaidItemList
     */
    results: Array<PlaidItem>;
}

/**
 * Check if a given object implements the PaginatedPlaidItemList interface.
 */
export function instanceOfPaginatedPlaidItemList(value: object): value is PaginatedPlaidItemList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedPlaidItemListFromJSON(json: any): PaginatedPlaidItemList {
    return PaginatedPlaidItemListFromJSONTyped(json, false);
}

export function PaginatedPlaidItemListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPlaidItemList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(PlaidItemFromJSON)),
    };
}

  export function PaginatedPlaidItemListToJSON(json: any): PaginatedPlaidItemList {
      return PaginatedPlaidItemListToJSONTyped(json, false);
  }

  export function PaginatedPlaidItemListToJSONTyped(value?: PaginatedPlaidItemList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(PlaidItemToJSON)),
    };
}

