/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaidAccount } from './PlaidAccount';
import {
    PlaidAccountFromJSON,
    PlaidAccountFromJSONTyped,
    PlaidAccountToJSON,
    PlaidAccountToJSONTyped,
} from './PlaidAccount';

/**
 * 
 * @export
 * @interface PaginatedPlaidAccountList
 */
export interface PaginatedPlaidAccountList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedPlaidAccountList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlaidAccountList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedPlaidAccountList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<PlaidAccount>}
     * @memberof PaginatedPlaidAccountList
     */
    results: Array<PlaidAccount>;
}

/**
 * Check if a given object implements the PaginatedPlaidAccountList interface.
 */
export function instanceOfPaginatedPlaidAccountList(value: object): value is PaginatedPlaidAccountList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedPlaidAccountListFromJSON(json: any): PaginatedPlaidAccountList {
    return PaginatedPlaidAccountListFromJSONTyped(json, false);
}

export function PaginatedPlaidAccountListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedPlaidAccountList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(PlaidAccountFromJSON)),
    };
}

  export function PaginatedPlaidAccountListToJSON(json: any): PaginatedPlaidAccountList {
      return PaginatedPlaidAccountListToJSONTyped(json, false);
  }

  export function PaginatedPlaidAccountListToJSONTyped(value?: PaginatedPlaidAccountList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(PlaidAccountToJSON)),
    };
}

