/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuditEvent } from './AuditEvent';
import {
    AuditEventFromJSON,
    AuditEventFromJSONTyped,
    AuditEventToJSON,
    AuditEventToJSONTyped,
} from './AuditEvent';

/**
 * 
 * @export
 * @interface PaginatedAuditEventList
 */
export interface PaginatedAuditEventList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAuditEventList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAuditEventList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAuditEventList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AuditEvent>}
     * @memberof PaginatedAuditEventList
     */
    results: Array<AuditEvent>;
}

/**
 * Check if a given object implements the PaginatedAuditEventList interface.
 */
export function instanceOfPaginatedAuditEventList(value: object): value is PaginatedAuditEventList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAuditEventListFromJSON(json: any): PaginatedAuditEventList {
    return PaginatedAuditEventListFromJSONTyped(json, false);
}

export function PaginatedAuditEventListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAuditEventList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AuditEventFromJSON)),
    };
}

  export function PaginatedAuditEventListToJSON(json: any): PaginatedAuditEventList {
      return PaginatedAuditEventListToJSONTyped(json, false);
  }

  export function PaginatedAuditEventListToJSONTyped(value?: PaginatedAuditEventList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AuditEventToJSON)),
    };
}

