/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountGroup } from './AccountGroup';
import {
    AccountGroupFromJSON,
    AccountGroupFromJSONTyped,
    AccountGroupToJSON,
    AccountGroupToJSONTyped,
} from './AccountGroup';

/**
 * 
 * @export
 * @interface PaginatedAccountGroupList
 */
export interface PaginatedAccountGroupList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAccountGroupList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAccountGroupList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAccountGroupList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AccountGroup>}
     * @memberof PaginatedAccountGroupList
     */
    results: Array<AccountGroup>;
}

/**
 * Check if a given object implements the PaginatedAccountGroupList interface.
 */
export function instanceOfPaginatedAccountGroupList(value: object): value is PaginatedAccountGroupList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAccountGroupListFromJSON(json: any): PaginatedAccountGroupList {
    return PaginatedAccountGroupListFromJSONTyped(json, false);
}

export function PaginatedAccountGroupListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAccountGroupList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AccountGroupFromJSON)),
    };
}

  export function PaginatedAccountGroupListToJSON(json: any): PaginatedAccountGroupList {
      return PaginatedAccountGroupListToJSONTyped(json, false);
  }

  export function PaginatedAccountGroupListToJSONTyped(value?: PaginatedAccountGroupList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AccountGroupToJSON)),
    };
}

