/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankFeedRow } from './BankFeedRow';
import {
    BankFeedRowFromJSON,
    BankFeedRowFromJSONTyped,
    BankFeedRowToJSON,
    BankFeedRowToJSONTyped,
} from './BankFeedRow';

/**
 * 
 * @export
 * @interface PaginatedBankFeedRowList
 */
export interface PaginatedBankFeedRowList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedBankFeedRowList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBankFeedRowList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBankFeedRowList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<BankFeedRow>}
     * @memberof PaginatedBankFeedRowList
     */
    results: Array<BankFeedRow>;
}

/**
 * Check if a given object implements the PaginatedBankFeedRowList interface.
 */
export function instanceOfPaginatedBankFeedRowList(value: object): value is PaginatedBankFeedRowList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedBankFeedRowListFromJSON(json: any): PaginatedBankFeedRowList {
    return PaginatedBankFeedRowListFromJSONTyped(json, false);
}

export function PaginatedBankFeedRowListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBankFeedRowList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(BankFeedRowFromJSON)),
    };
}

  export function PaginatedBankFeedRowListToJSON(json: any): PaginatedBankFeedRowList {
      return PaginatedBankFeedRowListToJSONTyped(json, false);
  }

  export function PaginatedBankFeedRowListToJSONTyped(value?: PaginatedBankFeedRowList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(BankFeedRowToJSON)),
    };
}

