/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for a parsed transaction in preview.
 * @export
 * @interface ParsedTransaction
 */
export interface ParsedTransaction {
    /**
     * Row number in original file
     * @type {number}
     * @memberof ParsedTransaction
     */
    rowNumber: number;
    /**
     * Parsed date
     * @type {Date}
     * @memberof ParsedTransaction
     */
    date: Date | null;
    /**
     * Transaction description
     * @type {string}
     * @memberof ParsedTransaction
     */
    description: string | null;
    /**
     * Payee name
     * @type {string}
     * @memberof ParsedTransaction
     */
    payee: string | null;
    /**
     * Original category name
     * @type {string}
     * @memberof ParsedTransaction
     */
    category: string | null;
    /**
     * Parsed amount
     * @type {string}
     * @memberof ParsedTransaction
     */
    amount: string | null;
    /**
     * Error message for this row
     * @type {string}
     * @memberof ParsedTransaction
     */
    error: string | null;
    /**
     * Matched/mapped category account ID
     * @type {number}
     * @memberof ParsedTransaction
     */
    matchedCategoryId: number | null;
    /**
     * Whether this may be a duplicate
     * @type {boolean}
     * @memberof ParsedTransaction
     */
    isPotentialDuplicate: boolean;
}

/**
 * Check if a given object implements the ParsedTransaction interface.
 */
export function instanceOfParsedTransaction(value: object): value is ParsedTransaction {
    if (!('rowNumber' in value) || value['rowNumber'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('payee' in value) || value['payee'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('matchedCategoryId' in value) || value['matchedCategoryId'] === undefined) return false;
    if (!('isPotentialDuplicate' in value) || value['isPotentialDuplicate'] === undefined) return false;
    return true;
}

export function ParsedTransactionFromJSON(json: any): ParsedTransaction {
    return ParsedTransactionFromJSONTyped(json, false);
}

export function ParsedTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParsedTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'rowNumber': json['row_number'],
        'date': (json['date'] == null ? null : new Date(json['date'])),
        'description': json['description'],
        'payee': json['payee'],
        'category': json['category'],
        'amount': json['amount'],
        'error': json['error'],
        'matchedCategoryId': json['matched_category_id'],
        'isPotentialDuplicate': json['is_potential_duplicate'],
    };
}

  export function ParsedTransactionToJSON(json: any): ParsedTransaction {
      return ParsedTransactionToJSONTyped(json, false);
  }

  export function ParsedTransactionToJSONTyped(value?: ParsedTransaction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'row_number': value['rowNumber'],
        'date': (value['date'] == null ? null : (value['date'] as any).toISOString().substring(0,10)),
        'description': value['description'],
        'payee': value['payee'],
        'category': value['category'],
        'amount': value['amount'],
        'error': value['error'],
        'matched_category_id': value['matchedCategoryId'],
        'is_potential_duplicate': value['isPotentialDuplicate'],
    };
}

