/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SimpleAccount } from './SimpleAccount';
import {
    SimpleAccountFromJSON,
    SimpleAccountFromJSONTyped,
    SimpleAccountToJSON,
    SimpleAccountToJSONTyped,
} from './SimpleAccount';
import type { BankFeedRowSourceEnum } from './BankFeedRowSourceEnum';
import {
    BankFeedRowSourceEnumFromJSON,
    BankFeedRowSourceEnumFromJSONTyped,
    BankFeedRowSourceEnumToJSON,
    BankFeedRowSourceEnumToJSONTyped,
} from './BankFeedRowSourceEnum';

/**
 * Unified bank feed row serializer.
 * This is NOT a model - it's a projection that combines data from
 * JournalLine (ledger) and BankTransaction (bank feed staging).
 * @export
 * @interface PatchedBankFeedRow
 */
export interface PatchedBankFeedRow {
    /**
     * Composite ID: 'ledger-{id}' or 'plaid-{id}'
     * @type {string}
     * @memberof PatchedBankFeedRow
     */
    id?: string;
    /**
     * Source of this row
     * 
     * * `ledger` - ledger
     * * `plaid` - plaid
     * * `csv` - csv
     * * `system` - system
     * @type {BankFeedRowSourceEnum}
     * @memberof PatchedBankFeedRow
     */
    source?: BankFeedRowSourceEnum;
    /**
     * Transaction date
     * @type {Date}
     * @memberof PatchedBankFeedRow
     */
    postedDate?: Date;
    /**
     * Authorization date (Plaid only)
     * @type {Date}
     * @memberof PatchedBankFeedRow
     */
    authorizedDate?: Date | null;
    /**
     * Transaction description
     * @type {string}
     * @memberof PatchedBankFeedRow
     */
    description?: string;
    /**
     * Merchant name
     * @type {string}
     * @memberof PatchedBankFeedRow
     */
    merchantName?: string | null;
    /**
     * The account this transaction affects
     * @type {SimpleAccount}
     * @memberof PatchedBankFeedRow
     */
    account?: SimpleAccount;
    /**
     * Category account (null if uncategorized)
     * @type {SimpleAccount}
     * @memberof PatchedBankFeedRow
     */
    category?: SimpleAccount | null;
    /**
     * Money coming in
     * @type {string}
     * @memberof PatchedBankFeedRow
     */
    inflow?: string;
    /**
     * Money going out
     * @type {string}
     * @memberof PatchedBankFeedRow
     */
    outflow?: string;
    /**
     * Whether transaction is pending
     * @type {boolean}
     * @memberof PatchedBankFeedRow
     */
    isPending?: boolean;
    /**
     * Whether transaction is cleared
     * @type {boolean}
     * @memberof PatchedBankFeedRow
     */
    isCleared?: boolean;
    /**
     * Whether transaction is archived
     * @type {boolean}
     * @memberof PatchedBankFeedRow
     */
    isArchived?: boolean;
    /**
     * Whether transaction is reconciled
     * @type {boolean}
     * @memberof PatchedBankFeedRow
     */
    isReconciled?: boolean;
    /**
     * Payee name (maps to merchant_name)
     * @type {string}
     * @memberof PatchedBankFeedRow
     */
    payee?: string | null;
    /**
     * Payment channel (Plaid)
     * @type {string}
     * @memberof PatchedBankFeedRow
     */
    paymentChannel?: string | null;
    /**
     * Categorization confidence
     * @type {string}
     * @memberof PatchedBankFeedRow
     */
    confidence?: string | null;
    /**
     * ID of imported tx (if bank feed)
     * @type {number}
     * @memberof PatchedBankFeedRow
     */
    importedTransactionId?: number | null;
    /**
     * ID of linked journal entry (if categorized)
     * @type {number}
     * @memberof PatchedBankFeedRow
     */
    journalEntryId?: number | null;
    /**
     * Whether this row can be edited
     * @type {boolean}
     * @memberof PatchedBankFeedRow
     */
    isEditable?: boolean;
}



/**
 * Check if a given object implements the PatchedBankFeedRow interface.
 */
export function instanceOfPatchedBankFeedRow(value: object): value is PatchedBankFeedRow {
    return true;
}

export function PatchedBankFeedRowFromJSON(json: any): PatchedBankFeedRow {
    return PatchedBankFeedRowFromJSONTyped(json, false);
}

export function PatchedBankFeedRowFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedBankFeedRow {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'source': json['source'] == null ? undefined : BankFeedRowSourceEnumFromJSON(json['source']),
        'postedDate': json['posted_date'] == null ? undefined : (new Date(json['posted_date'])),
        'authorizedDate': json['authorized_date'] == null ? undefined : (new Date(json['authorized_date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'merchantName': json['merchant_name'] == null ? undefined : json['merchant_name'],
        'account': json['account'] == null ? undefined : SimpleAccountFromJSON(json['account']),
        'category': json['category'] == null ? undefined : SimpleAccountFromJSON(json['category']),
        'inflow': json['inflow'] == null ? undefined : json['inflow'],
        'outflow': json['outflow'] == null ? undefined : json['outflow'],
        'isPending': json['is_pending'] == null ? undefined : json['is_pending'],
        'isCleared': json['is_cleared'] == null ? undefined : json['is_cleared'],
        'isArchived': json['is_archived'] == null ? undefined : json['is_archived'],
        'isReconciled': json['is_reconciled'] == null ? undefined : json['is_reconciled'],
        'payee': json['payee'] == null ? undefined : json['payee'],
        'paymentChannel': json['payment_channel'] == null ? undefined : json['payment_channel'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'importedTransactionId': json['imported_transaction_id'] == null ? undefined : json['imported_transaction_id'],
        'journalEntryId': json['journal_entry_id'] == null ? undefined : json['journal_entry_id'],
        'isEditable': json['is_editable'] == null ? undefined : json['is_editable'],
    };
}

  export function PatchedBankFeedRowToJSON(json: any): PatchedBankFeedRow {
      return PatchedBankFeedRowToJSONTyped(json, false);
  }

  export function PatchedBankFeedRowToJSONTyped(value?: PatchedBankFeedRow | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'source': BankFeedRowSourceEnumToJSON(value['source']),
        'posted_date': value['postedDate'] == null ? undefined : ((value['postedDate']).toISOString().substring(0,10)),
        'authorized_date': value['authorizedDate'] == null ? undefined : ((value['authorizedDate'] as any).toISOString().substring(0,10)),
        'description': value['description'],
        'merchant_name': value['merchantName'],
        'account': SimpleAccountToJSON(value['account']),
        'category': SimpleAccountToJSON(value['category']),
        'inflow': value['inflow'],
        'outflow': value['outflow'],
        'is_pending': value['isPending'],
        'is_cleared': value['isCleared'],
        'is_archived': value['isArchived'],
        'is_reconciled': value['isReconciled'],
        'payee': value['payee'],
        'payment_channel': value['paymentChannel'],
        'confidence': value['confidence'],
        'imported_transaction_id': value['importedTransactionId'],
        'journal_entry_id': value['journalEntryId'],
        'is_editable': value['isEditable'],
    };
}

