/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Simplified line serializer for journal lines.
 * Presents journal lines in a transaction-like format with data from:
 * - The journal line itself (account, inflow, outflow, is_cleared, is_reconciled)
 * - The parent journal entry (date, description, payee, source)
 * - The sibling journal line (category)
 * 
 * This is designed for displaying transactions from the perspective of a single account,
 * similar to a bank register view.
 * 
 * For create/update operations:
 * - date: transaction date
 * - account: the account for this line
 * - category: the account for the sibling line
 * - inflow: debit amount (money coming in)
 * - outflow: credit amount (money going out)
 * - description: transaction description
 * - payee: optional payee
 * - is_cleared: whether the line is cleared
 * - is_reconciled: whether the line is reconciled
 * @export
 * @interface PatchedSimpleLine
 */
export interface PatchedSimpleLine {
    /**
     * 
     * @type {number}
     * @memberof PatchedSimpleLine
     */
    readonly lineId?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedSimpleLine
     */
    readonly journalId?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSimpleLine
     */
    date?: Date;
    /**
     * The account for this line
     * @type {number}
     * @memberof PatchedSimpleLine
     */
    account?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleLine
     */
    readonly accountName?: string;
    /**
     * The category account (for the sibling line)
     * @type {number}
     * @memberof PatchedSimpleLine
     */
    category?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleLine
     */
    readonly categoryName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleLine
     */
    inflow?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleLine
     */
    outflow?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleLine
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedSimpleLine
     */
    payee?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleLine
     */
    readonly payeeName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSimpleLine
     */
    isCleared?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSimpleLine
     */
    isReconciled?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedSimpleLine
     */
    isArchived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleLine
     */
    readonly source?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleLine
     */
    readonly status?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSimpleLine
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSimpleLine
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the PatchedSimpleLine interface.
 */
export function instanceOfPatchedSimpleLine(value: object): value is PatchedSimpleLine {
    return true;
}

export function PatchedSimpleLineFromJSON(json: any): PatchedSimpleLine {
    return PatchedSimpleLineFromJSONTyped(json, false);
}

export function PatchedSimpleLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSimpleLine {
    if (json == null) {
        return json;
    }
    return {
        
        'lineId': json['line_id'] == null ? undefined : json['line_id'],
        'journalId': json['journal_id'] == null ? undefined : json['journal_id'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'account': json['account'] == null ? undefined : json['account'],
        'accountName': json['account_name'] == null ? undefined : json['account_name'],
        'category': json['category'] == null ? undefined : json['category'],
        'categoryName': json['category_name'] == null ? undefined : json['category_name'],
        'inflow': json['inflow'] == null ? undefined : json['inflow'],
        'outflow': json['outflow'] == null ? undefined : json['outflow'],
        'description': json['description'] == null ? undefined : json['description'],
        'payee': json['payee'] == null ? undefined : json['payee'],
        'payeeName': json['payee_name'] == null ? undefined : json['payee_name'],
        'isCleared': json['is_cleared'] == null ? undefined : json['is_cleared'],
        'isReconciled': json['is_reconciled'] == null ? undefined : json['is_reconciled'],
        'isArchived': json['is_archived'] == null ? undefined : json['is_archived'],
        'source': json['source'] == null ? undefined : json['source'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

  export function PatchedSimpleLineToJSON(json: any): PatchedSimpleLine {
      return PatchedSimpleLineToJSONTyped(json, false);
  }

  export function PatchedSimpleLineToJSONTyped(value?: Omit<PatchedSimpleLine, 'line_id'|'journal_id'|'account_name'|'category_name'|'payee_name'|'source'|'status'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'account': value['account'],
        'category': value['category'],
        'inflow': value['inflow'],
        'outflow': value['outflow'],
        'description': value['description'],
        'payee': value['payee'],
        'is_cleared': value['isCleared'],
        'is_reconciled': value['isReconciled'],
        'is_archived': value['isArchived'],
    };
}

