/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Simplified transaction serializer for easy client-side usage.
 * Converts between simple transaction format and journal entry format.
 * 
 * Simple format:
 * - date: transaction date
 * - account: the account money is moving from/to (e.g., bank account)
 * - category: the category account (e.g., groceries, salary)
 * - amount: positive amount
 * - description: transaction description
 * - payee: optional payee ID
 * 
 * This gets converted to a journal entry with 2 lines based on account types.
 * @export
 * @interface PatchedSimpleTransaction
 */
export interface PatchedSimpleTransaction {
    /**
     * 
     * @type {number}
     * @memberof PatchedSimpleTransaction
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSimpleTransaction
     */
    date?: Date;
    /**
     * The account money is moving from/to (e.g., bank account)
     * @type {number}
     * @memberof PatchedSimpleTransaction
     */
    account?: number;
    /**
     * The category account (e.g., groceries, salary)
     * @type {number}
     * @memberof PatchedSimpleTransaction
     */
    category?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleTransaction
     */
    amount?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleTransaction
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedSimpleTransaction
     */
    payee?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleTransaction
     */
    readonly accountName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleTransaction
     */
    readonly categoryName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleTransaction
     */
    readonly payeeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedSimpleTransaction
     */
    readonly status?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSimpleTransaction
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedSimpleTransaction
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the PatchedSimpleTransaction interface.
 */
export function instanceOfPatchedSimpleTransaction(value: object): value is PatchedSimpleTransaction {
    return true;
}

export function PatchedSimpleTransactionFromJSON(json: any): PatchedSimpleTransaction {
    return PatchedSimpleTransactionFromJSONTyped(json, false);
}

export function PatchedSimpleTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedSimpleTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'account': json['account'] == null ? undefined : json['account'],
        'category': json['category'] == null ? undefined : json['category'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'description': json['description'] == null ? undefined : json['description'],
        'payee': json['payee'] == null ? undefined : json['payee'],
        'accountName': json['account_name'] == null ? undefined : json['account_name'],
        'categoryName': json['category_name'] == null ? undefined : json['category_name'],
        'payeeName': json['payee_name'] == null ? undefined : json['payee_name'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

  export function PatchedSimpleTransactionToJSON(json: any): PatchedSimpleTransaction {
      return PatchedSimpleTransactionToJSONTyped(json, false);
  }

  export function PatchedSimpleTransactionToJSONTyped(value?: Omit<PatchedSimpleTransaction, 'id'|'account_name'|'category_name'|'payee_name'|'status'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': value['date'] == null ? undefined : ((value['date']).toISOString().substring(0,10)),
        'account': value['account'],
        'category': value['category'],
        'amount': value['amount'],
        'description': value['description'],
        'payee': value['payee'],
    };
}

