/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for PlaidItem model.
 * @export
 * @interface PlaidItem
 */
export interface PlaidItem {
    /**
     * 
     * @type {number}
     * @memberof PlaidItem
     */
    readonly id: number;
    /**
     * Plaid's unique identifier for this item
     * @type {string}
     * @memberof PlaidItem
     */
    plaidItemId: string;
    /**
     * Name of the financial institution
     * @type {string}
     * @memberof PlaidItem
     */
    institutionName: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidItem
     */
    readonly isActive: string;
    /**
     * 
     * @type {Date}
     * @memberof PlaidItem
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlaidItem
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the PlaidItem interface.
 */
export function instanceOfPlaidItem(value: object): value is PlaidItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('plaidItemId' in value) || value['plaidItemId'] === undefined) return false;
    if (!('institutionName' in value) || value['institutionName'] === undefined) return false;
    if (!('isActive' in value) || value['isActive'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PlaidItemFromJSON(json: any): PlaidItem {
    return PlaidItemFromJSONTyped(json, false);
}

export function PlaidItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'plaidItemId': json['plaid_item_id'],
        'institutionName': json['institution_name'],
        'isActive': json['is_active'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function PlaidItemToJSON(json: any): PlaidItem {
      return PlaidItemToJSONTyped(json, false);
  }

  export function PlaidItemToJSONTyped(value?: Omit<PlaidItem, 'id'|'is_active'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plaid_item_id': value['plaidItemId'],
        'institution_name': value['institutionName'],
    };
}

