/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaidAccount } from './PlaidAccount';
import {
    PlaidAccountFromJSON,
    PlaidAccountFromJSONTyped,
    PlaidAccountToJSON,
    PlaidAccountToJSONTyped,
} from './PlaidAccount';

/**
 * Serializer for PlaidTransaction model.
 * @export
 * @interface PlaidTransaction
 */
export interface PlaidTransaction {
    /**
     * 
     * @type {number}
     * @memberof PlaidTransaction
     */
    readonly id: number;
    /**
     * Plaid's unique identifier for this transaction
     * @type {string}
     * @memberof PlaidTransaction
     */
    plaidTransactionId: string;
    /**
     * The Plaid account this transaction belongs to
     * @type {number}
     * @memberof PlaidTransaction
     */
    plaidAccount: number;
    /**
     * 
     * @type {PlaidAccount}
     * @memberof PlaidTransaction
     */
    readonly plaidAccountDetails: PlaidAccount;
    /**
     * ISO currency code
     * @type {string}
     * @memberof PlaidTransaction
     */
    isoCurrencyCode?: string | null;
    /**
     * Authorization date
     * @type {Date}
     * @memberof PlaidTransaction
     */
    authorizedDate?: Date | null;
    /**
     * Whether this transaction is pending
     * @type {boolean}
     * @memberof PlaidTransaction
     */
    pending?: boolean;
    /**
     * Plaid's personal finance category
     * @type {string}
     * @memberof PlaidTransaction
     */
    personalFinanceCategory?: string | null;
    /**
     * Confidence level of Plaid's categorization
     * @type {string}
     * @memberof PlaidTransaction
     */
    categoryConfidence?: string | null;
    /**
     * Payment channel
     * @type {string}
     * @memberof PlaidTransaction
     */
    paymentChannel?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PlaidTransaction
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlaidTransaction
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the PlaidTransaction interface.
 */
export function instanceOfPlaidTransaction(value: object): value is PlaidTransaction {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('plaidTransactionId' in value) || value['plaidTransactionId'] === undefined) return false;
    if (!('plaidAccount' in value) || value['plaidAccount'] === undefined) return false;
    if (!('plaidAccountDetails' in value) || value['plaidAccountDetails'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function PlaidTransactionFromJSON(json: any): PlaidTransaction {
    return PlaidTransactionFromJSONTyped(json, false);
}

export function PlaidTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'plaidTransactionId': json['plaid_transaction_id'],
        'plaidAccount': json['plaid_account'],
        'plaidAccountDetails': PlaidAccountFromJSON(json['plaid_account_details']),
        'isoCurrencyCode': json['iso_currency_code'] == null ? undefined : json['iso_currency_code'],
        'authorizedDate': json['authorized_date'] == null ? undefined : (new Date(json['authorized_date'])),
        'pending': json['pending'] == null ? undefined : json['pending'],
        'personalFinanceCategory': json['personal_finance_category'] == null ? undefined : json['personal_finance_category'],
        'categoryConfidence': json['category_confidence'] == null ? undefined : json['category_confidence'],
        'paymentChannel': json['payment_channel'] == null ? undefined : json['payment_channel'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function PlaidTransactionToJSON(json: any): PlaidTransaction {
      return PlaidTransactionToJSONTyped(json, false);
  }

  export function PlaidTransactionToJSONTyped(value?: Omit<PlaidTransaction, 'id'|'plaid_account_details'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'plaid_transaction_id': value['plaidTransactionId'],
        'plaid_account': value['plaidAccount'],
        'iso_currency_code': value['isoCurrencyCode'],
        'authorized_date': value['authorizedDate'] == null ? undefined : ((value['authorizedDate'] as any).toISOString().substring(0,10)),
        'pending': value['pending'],
        'personal_finance_category': value['personalFinanceCategory'],
        'category_confidence': value['categoryConfidence'],
        'payment_channel': value['paymentChannel'],
    };
}

