/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaidItemsSync200Response
 */
export interface PlaidItemsSync200Response {
    /**
     * 
     * @type {string}
     * @memberof PlaidItemsSync200Response
     */
    taskId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidItemsSync200Response
     */
    status?: string;
}

/**
 * Check if a given object implements the PlaidItemsSync200Response interface.
 */
export function instanceOfPlaidItemsSync200Response(value: object): value is PlaidItemsSync200Response {
    return true;
}

export function PlaidItemsSync200ResponseFromJSON(json: any): PlaidItemsSync200Response {
    return PlaidItemsSync200ResponseFromJSONTyped(json, false);
}

export function PlaidItemsSync200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidItemsSync200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'taskId': json['task_id'] == null ? undefined : json['task_id'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

  export function PlaidItemsSync200ResponseToJSON(json: any): PlaidItemsSync200Response {
      return PlaidItemsSync200ResponseToJSONTyped(json, false);
  }

  export function PlaidItemsSync200ResponseToJSONTyped(value?: PlaidItemsSync200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'task_id': value['taskId'],
        'status': value['status'],
    };
}

