/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReconciliationTick
 */
export interface ReconciliationTick {
    /**
     * 
     * @type {Array<number>}
     * @memberof ReconciliationTick
     */
    lineIds: Array<number>;
    /**
     * 
     * @type {boolean}
     * @memberof ReconciliationTick
     */
    ticked: boolean;
}

/**
 * Check if a given object implements the ReconciliationTick interface.
 */
export function instanceOfReconciliationTick(value: object): value is ReconciliationTick {
    if (!('lineIds' in value) || value['lineIds'] === undefined) return false;
    if (!('ticked' in value) || value['ticked'] === undefined) return false;
    return true;
}

export function ReconciliationTickFromJSON(json: any): ReconciliationTick {
    return ReconciliationTickFromJSONTyped(json, false);
}

export function ReconciliationTickFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReconciliationTick {
    if (json == null) {
        return json;
    }
    return {
        
        'lineIds': json['line_ids'],
        'ticked': json['ticked'],
    };
}

  export function ReconciliationTickToJSON(json: any): ReconciliationTick {
      return ReconciliationTickToJSONTyped(json, false);
  }

  export function ReconciliationTickToJSONTyped(value?: ReconciliationTick | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'line_ids': value['lineIds'],
        'ticked': value['ticked'],
    };
}

