/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReconciliationTickThrough
 */
export interface ReconciliationTickThrough {
    /**
     * 
     * @type {Date}
     * @memberof ReconciliationTickThrough
     */
    date: Date;
}

/**
 * Check if a given object implements the ReconciliationTickThrough interface.
 */
export function instanceOfReconciliationTickThrough(value: object): value is ReconciliationTickThrough {
    if (!('date' in value) || value['date'] === undefined) return false;
    return true;
}

export function ReconciliationTickThroughFromJSON(json: any): ReconciliationTickThrough {
    return ReconciliationTickThroughFromJSONTyped(json, false);
}

export function ReconciliationTickThroughFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReconciliationTickThrough {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
    };
}

  export function ReconciliationTickThroughToJSON(json: any): ReconciliationTickThrough {
      return ReconciliationTickThroughToJSONTyped(json, false);
  }

  export function ReconciliationTickThroughToJSONTyped(value?: ReconciliationTickThrough | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString().substring(0,10)),
    };
}

