/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReconciliationStart
 */
export interface ReconciliationStart {
    /**
     * Asset or liability account id
     * @type {number}
     * @memberof ReconciliationStart
     */
    account: number;
    /**
     * 
     * @type {Date}
     * @memberof ReconciliationStart
     */
    statementDate: Date;
    /**
     * Closing balance as printed on the statement
     * @type {string}
     * @memberof ReconciliationStart
     */
    statementBalance: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof ReconciliationStart
     */
    lineIds?: Array<number>;
}

/**
 * Check if a given object implements the ReconciliationStart interface.
 */
export function instanceOfReconciliationStart(value: object): value is ReconciliationStart {
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('statementDate' in value) || value['statementDate'] === undefined) return false;
    if (!('statementBalance' in value) || value['statementBalance'] === undefined) return false;
    return true;
}

export function ReconciliationStartFromJSON(json: any): ReconciliationStart {
    return ReconciliationStartFromJSONTyped(json, false);
}

export function ReconciliationStartFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReconciliationStart {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'],
        'statementDate': (new Date(json['statement_date'])),
        'statementBalance': json['statement_balance'],
        'lineIds': json['line_ids'] == null ? undefined : json['line_ids'],
    };
}

  export function ReconciliationStartToJSON(json: any): ReconciliationStart {
      return ReconciliationStartToJSONTyped(json, false);
  }

  export function ReconciliationStartToJSONTyped(value?: ReconciliationStart | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account': value['account'],
        'statement_date': ((value['statementDate']).toISOString().substring(0,10)),
        'statement_balance': value['statementBalance'],
        'line_ids': value['lineIds'],
    };
}

