/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Simplified line serializer for journal lines.
 * Presents journal lines in a transaction-like format with data from:
 * - The journal line itself (account, inflow, outflow, is_cleared, is_reconciled)
 * - The parent journal entry (date, description, payee, source)
 * - The sibling journal line (category)
 * 
 * This is designed for displaying transactions from the perspective of a single account,
 * similar to a bank register view.
 * 
 * For create/update operations:
 * - date: transaction date
 * - account: the account for this line
 * - category: the account for the sibling line
 * - inflow: debit amount (money coming in)
 * - outflow: credit amount (money going out)
 * - description: transaction description
 * - payee: optional payee
 * - is_cleared: whether the line is cleared
 * - is_reconciled: whether the line is reconciled
 * @export
 * @interface SimpleLine
 */
export interface SimpleLine {
    /**
     * 
     * @type {number}
     * @memberof SimpleLine
     */
    readonly lineId: number;
    /**
     * 
     * @type {number}
     * @memberof SimpleLine
     */
    readonly journalId: number;
    /**
     * 
     * @type {Date}
     * @memberof SimpleLine
     */
    date: Date;
    /**
     * The account for this line
     * @type {number}
     * @memberof SimpleLine
     */
    account: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleLine
     */
    readonly accountName: string;
    /**
     * The category account (for the sibling line)
     * @type {number}
     * @memberof SimpleLine
     */
    category: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleLine
     */
    readonly categoryName: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleLine
     */
    inflow?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleLine
     */
    outflow?: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleLine
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof SimpleLine
     */
    payee?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SimpleLine
     */
    readonly payeeName: string;
    /**
     * 
     * @type {boolean}
     * @memberof SimpleLine
     */
    isCleared?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SimpleLine
     */
    isReconciled?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof SimpleLine
     */
    reconciledDate?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof SimpleLine
     */
    isArchived?: boolean;
    /**
     * 
     * @type {string}
     * @memberof SimpleLine
     */
    readonly source: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleLine
     */
    readonly status: string;
    /**
     * 
     * @type {Date}
     * @memberof SimpleLine
     */
    readonly createdAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof SimpleLine
     */
    readonly updatedAt: Date;
}

/**
 * Check if a given object implements the SimpleLine interface.
 */
export function instanceOfSimpleLine(value: object): value is SimpleLine {
    if (!('lineId' in value) || value['lineId'] === undefined) return false;
    if (!('journalId' in value) || value['journalId'] === undefined) return false;
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('account' in value) || value['account'] === undefined) return false;
    if (!('accountName' in value) || value['accountName'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('categoryName' in value) || value['categoryName'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('payeeName' in value) || value['payeeName'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SimpleLineFromJSON(json: any): SimpleLine {
    return SimpleLineFromJSONTyped(json, false);
}

export function SimpleLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleLine {
    if (json == null) {
        return json;
    }
    return {
        
        'lineId': json['line_id'],
        'journalId': json['journal_id'],
        'date': (new Date(json['date'])),
        'account': json['account'],
        'accountName': json['account_name'],
        'category': json['category'],
        'categoryName': json['category_name'],
        'inflow': json['inflow'] == null ? undefined : json['inflow'],
        'outflow': json['outflow'] == null ? undefined : json['outflow'],
        'description': json['description'],
        'payee': json['payee'] == null ? undefined : json['payee'],
        'payeeName': json['payee_name'],
        'isCleared': json['is_cleared'] == null ? undefined : json['is_cleared'],
        'isReconciled': json['is_reconciled'] == null ? undefined : json['is_reconciled'],
        'reconciledDate': json['reconciled_date'] == null ? undefined : (new Date(json['reconciled_date'])),
        'isArchived': json['is_archived'] == null ? undefined : json['is_archived'],
        'source': json['source'],
        'status': json['status'],
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

  export function SimpleLineToJSON(json: any): SimpleLine {
      return SimpleLineToJSONTyped(json, false);
  }

  export function SimpleLineToJSONTyped(value?: Omit<SimpleLine, 'line_id'|'journal_id'|'account_name'|'category_name'|'payee_name'|'source'|'status'|'created_at'|'updated_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString().substring(0,10)),
        'account': value['account'],
        'category': value['category'],
        'inflow': value['inflow'],
        'outflow': value['outflow'],
        'description': value['description'],
        'payee': value['payee'],
        'is_cleared': value['isCleared'],
        'is_reconciled': value['isReconciled'],
        'reconciled_date': value['reconciledDate'] == null ? undefined : ((value['reconciledDate'] as any).toISOString().substring(0,10)),
        'is_archived': value['isArchived'],
    };
}

