/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleLinesRecategorize200Response
 */
export interface SimpleLinesRecategorize200Response {
    /**
     * 
     * @type {string}
     * @memberof SimpleLinesRecategorize200Response
     */
    status?: string;
    /**
     * 
     * @type {number}
     * @memberof SimpleLinesRecategorize200Response
     */
    lineId?: number;
}

/**
 * Check if a given object implements the SimpleLinesRecategorize200Response interface.
 */
export function instanceOfSimpleLinesRecategorize200Response(value: object): value is SimpleLinesRecategorize200Response {
    return true;
}

export function SimpleLinesRecategorize200ResponseFromJSON(json: any): SimpleLinesRecategorize200Response {
    return SimpleLinesRecategorize200ResponseFromJSONTyped(json, false);
}

export function SimpleLinesRecategorize200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleLinesRecategorize200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'lineId': json['line_id'] == null ? undefined : json['line_id'],
    };
}

  export function SimpleLinesRecategorize200ResponseToJSON(json: any): SimpleLinesRecategorize200Response {
      return SimpleLinesRecategorize200ResponseToJSONTyped(json, false);
  }

  export function SimpleLinesRecategorize200ResponseToJSONTyped(value?: SimpleLinesRecategorize200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'line_id': value['lineId'],
    };
}

