/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for Account model.
 * @export
 * @interface SimpleAccount
 */
export interface SimpleAccount {
    /**
     * 
     * @type {number}
     * @memberof SimpleAccount
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleAccount
     */
    name: string;
    /**
     * Account number (1000s for assets, 2000s for liabilities, etc.)
     * @type {string}
     * @memberof SimpleAccount
     */
    accountNumber: string;
    /**
     * Account group classification
     * @type {number}
     * @memberof SimpleAccount
     */
    accountGroup: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleAccount
     */
    readonly accountGroupName: string;
    /**
     * 
     * @type {string}
     * @memberof SimpleAccount
     */
    readonly accountType: string;
    /**
     * Whether this account has a bank feed
     * @type {boolean}
     * @memberof SimpleAccount
     */
    hasFeed?: boolean;
    /**
     * Set to true to archive this item
     * @type {boolean}
     * @memberof SimpleAccount
     */
    isArchived?: boolean;
    /**
     * Date this item was archived
     * @type {Date}
     * @memberof SimpleAccount
     */
    readonly archivedAt: Date | null;
}

/**
 * Check if a given object implements the SimpleAccount interface.
 */
export function instanceOfSimpleAccount(value: object): value is SimpleAccount {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('accountNumber' in value) || value['accountNumber'] === undefined) return false;
    if (!('accountGroup' in value) || value['accountGroup'] === undefined) return false;
    if (!('accountGroupName' in value) || value['accountGroupName'] === undefined) return false;
    if (!('accountType' in value) || value['accountType'] === undefined) return false;
    if (!('archivedAt' in value) || value['archivedAt'] === undefined) return false;
    return true;
}

export function SimpleAccountFromJSON(json: any): SimpleAccount {
    return SimpleAccountFromJSONTyped(json, false);
}

export function SimpleAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'accountNumber': json['account_number'],
        'accountGroup': json['account_group'],
        'accountGroupName': json['account_group_name'],
        'accountType': json['account_type'],
        'hasFeed': json['has_feed'] == null ? undefined : json['has_feed'],
        'isArchived': json['is_archived'] == null ? undefined : json['is_archived'],
        'archivedAt': (json['archived_at'] == null ? null : new Date(json['archived_at'])),
    };
}

  export function SimpleAccountToJSON(json: any): SimpleAccount {
      return SimpleAccountToJSONTyped(json, false);
  }

  export function SimpleAccountToJSONTyped(value?: Omit<SimpleAccount, 'id'|'account_group_name'|'account_type'|'archived_at'> | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'account_number': value['accountNumber'],
        'account_group': value['accountGroup'],
        'has_feed': value['hasFeed'],
        'is_archived': value['isArchived'],
    };
}

