/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `manual` - Manual Entry
 * * `import` - Import
 * * `bank_match` - Bank Match
 * * `recurring` - Recurring Entry
 * @export
 */
export const SourceEnum = {
    Manual: 'manual',
    Import: 'import',
    BankMatch: 'bank_match',
    Recurring: 'recurring'
} as const;
export type SourceEnum = typeof SourceEnum[keyof typeof SourceEnum];


export function instanceOfSourceEnum(value: any): boolean {
    for (const key in SourceEnum) {
        if (Object.prototype.hasOwnProperty.call(SourceEnum, key)) {
            if (SourceEnum[key as keyof typeof SourceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SourceEnumFromJSON(json: any): SourceEnum {
    return SourceEnumFromJSONTyped(json, false);
}

export function SourceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceEnum {
    return json as SourceEnum;
}

export function SourceEnumToJSON(value?: SourceEnum | null): any {
    return value as any;
}

export function SourceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): SourceEnum {
    return value as SourceEnum;
}

