/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionsFacets200ResponseValuesInner } from './TransactionsFacets200ResponseValuesInner';
import {
    TransactionsFacets200ResponseValuesInnerFromJSON,
    TransactionsFacets200ResponseValuesInnerFromJSONTyped,
    TransactionsFacets200ResponseValuesInnerToJSON,
    TransactionsFacets200ResponseValuesInnerToJSONTyped,
} from './TransactionsFacets200ResponseValuesInner';

/**
 * 
 * @export
 * @interface TransactionsFacets200Response
 */
export interface TransactionsFacets200Response {
    /**
     * 
     * @type {string}
     * @memberof TransactionsFacets200Response
     */
    column?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionsFacets200Response
     */
    hierarchical?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionsFacets200Response
     */
    truncated?: boolean;
    /**
     * 
     * @type {Array<TransactionsFacets200ResponseValuesInner>}
     * @memberof TransactionsFacets200Response
     */
    values?: Array<TransactionsFacets200ResponseValuesInner>;
}

/**
 * Check if a given object implements the TransactionsFacets200Response interface.
 */
export function instanceOfTransactionsFacets200Response(value: object): value is TransactionsFacets200Response {
    return true;
}

export function TransactionsFacets200ResponseFromJSON(json: any): TransactionsFacets200Response {
    return TransactionsFacets200ResponseFromJSONTyped(json, false);
}

export function TransactionsFacets200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsFacets200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'column': json['column'] == null ? undefined : json['column'],
        'hierarchical': json['hierarchical'] == null ? undefined : json['hierarchical'],
        'truncated': json['truncated'] == null ? undefined : json['truncated'],
        'values': json['values'] == null ? undefined : ((json['values'] as Array<any>).map(TransactionsFacets200ResponseValuesInnerFromJSON)),
    };
}

  export function TransactionsFacets200ResponseToJSON(json: any): TransactionsFacets200Response {
      return TransactionsFacets200ResponseToJSONTyped(json, false);
  }

  export function TransactionsFacets200ResponseToJSONTyped(value?: TransactionsFacets200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'column': value['column'],
        'hierarchical': value['hierarchical'],
        'truncated': value['truncated'],
        'values': value['values'] == null ? undefined : ((value['values'] as Array<any>).map(TransactionsFacets200ResponseValuesInnerToJSON)),
    };
}

