/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Resolve a duplicate transfer by archiving one leg and keeping the other.
 * @export
 * @interface TransferResolveRequest
 */
export interface TransferResolveRequest {
    /**
     * BankTransaction id of the duplicate leg to archive
     * @type {number}
     * @memberof TransferResolveRequest
     */
    archiveId: number;
    /**
     * BankTransaction id of the leg to keep
     * @type {number}
     * @memberof TransferResolveRequest
     */
    keepId: number;
}

/**
 * Check if a given object implements the TransferResolveRequest interface.
 */
export function instanceOfTransferResolveRequest(value: object): value is TransferResolveRequest {
    if (!('archiveId' in value) || value['archiveId'] === undefined) return false;
    if (!('keepId' in value) || value['keepId'] === undefined) return false;
    return true;
}

export function TransferResolveRequestFromJSON(json: any): TransferResolveRequest {
    return TransferResolveRequestFromJSONTyped(json, false);
}

export function TransferResolveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferResolveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'archiveId': json['archive_id'],
        'keepId': json['keep_id'],
    };
}

  export function TransferResolveRequestToJSON(json: any): TransferResolveRequest {
      return TransferResolveRequestToJSONTyped(json, false);
  }

  export function TransferResolveRequestToJSONTyped(value?: TransferResolveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'archive_id': value['archiveId'],
        'keep_id': value['keepId'],
    };
}

