/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `void` - void
 * * `posted` - posted
 * @export
 */
export const TransactionStatusRequestStatusEnum = {
    Void: 'void',
    Posted: 'posted'
} as const;
export type TransactionStatusRequestStatusEnum = typeof TransactionStatusRequestStatusEnum[keyof typeof TransactionStatusRequestStatusEnum];


export function instanceOfTransactionStatusRequestStatusEnum(value: any): boolean {
    for (const key in TransactionStatusRequestStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(TransactionStatusRequestStatusEnum, key)) {
            if (TransactionStatusRequestStatusEnum[key as keyof typeof TransactionStatusRequestStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TransactionStatusRequestStatusEnumFromJSON(json: any): TransactionStatusRequestStatusEnum {
    return TransactionStatusRequestStatusEnumFromJSONTyped(json, false);
}

export function TransactionStatusRequestStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionStatusRequestStatusEnum {
    return json as TransactionStatusRequestStatusEnum;
}

export function TransactionStatusRequestStatusEnumToJSON(value?: TransactionStatusRequestStatusEnum | null): any {
    return value as any;
}

export function TransactionStatusRequestStatusEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): TransactionStatusRequestStatusEnum {
    return value as TransactionStatusRequestStatusEnum;
}

