/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionIds
 */
export interface TransactionIds {
    /**
     * 
     * @type {Array<number>}
     * @memberof TransactionIds
     */
    ids: Array<number>;
}

/**
 * Check if a given object implements the TransactionIds interface.
 */
export function instanceOfTransactionIds(value: object): value is TransactionIds {
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function TransactionIdsFromJSON(json: any): TransactionIds {
    return TransactionIdsFromJSONTyped(json, false);
}

export function TransactionIdsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionIds {
    if (json == null) {
        return json;
    }
    return {
        
        'ids': json['ids'],
    };
}

  export function TransactionIdsToJSON(json: any): TransactionIds {
      return TransactionIdsToJSONTyped(json, false);
  }

  export function TransactionIdsToJSONTyped(value?: TransactionIds | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ids': value['ids'],
    };
}

