/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransferProposalStatusEnum } from './TransferProposalStatusEnum';
import {
    TransferProposalStatusEnumFromJSON,
    TransferProposalStatusEnumFromJSONTyped,
    TransferProposalStatusEnumToJSON,
    TransferProposalStatusEnumToJSONTyped,
} from './TransferProposalStatusEnum';

/**
 * What Match would do with a suggested pair (decided server-side).
 * @export
 * @interface TransferProposal
 */
export interface TransferProposal {
    /**
     * ready: Match is available
     * 
     * * `ready` - ready
     * * `blocked` - blocked
     * @type {TransferProposalStatusEnum}
     * @memberof TransferProposal
     */
    status: TransferProposalStatusEnum;
    /**
     * Machine-readable reason (e.g. reconciled, split, outflow)
     * @type {string}
     * @memberof TransferProposal
     */
    code: string;
    /**
     * Why this leg is kept (a clause, when ready) or why Match is unavailable (when blocked)
     * @type {string}
     * @memberof TransferProposal
     */
    message: string;
    /**
     * BankTransaction id Match keeps
     * @type {number}
     * @memberof TransferProposal
     */
    keepId: number | null;
    /**
     * BankTransaction id Match archives
     * @type {number}
     * @memberof TransferProposal
     */
    archiveId: number | null;
}



/**
 * Check if a given object implements the TransferProposal interface.
 */
export function instanceOfTransferProposal(value: object): value is TransferProposal {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('keepId' in value) || value['keepId'] === undefined) return false;
    if (!('archiveId' in value) || value['archiveId'] === undefined) return false;
    return true;
}

export function TransferProposalFromJSON(json: any): TransferProposal {
    return TransferProposalFromJSONTyped(json, false);
}

export function TransferProposalFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferProposal {
    if (json == null) {
        return json;
    }
    return {
        
        'status': TransferProposalStatusEnumFromJSON(json['status']),
        'code': json['code'],
        'message': json['message'],
        'keepId': json['keep_id'],
        'archiveId': json['archive_id'],
    };
}

  export function TransferProposalToJSON(json: any): TransferProposal {
      return TransferProposalToJSONTyped(json, false);
  }

  export function TransferProposalToJSONTyped(value?: TransferProposal | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': TransferProposalStatusEnumToJSON(value['status']),
        'code': value['code'],
        'message': value['message'],
        'keep_id': value['keepId'],
        'archive_id': value['archiveId'],
    };
}

