/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Match a suggested pair: keep one leg, archive the other.
 * @export
 * @interface TransferMatchRequest
 */
export interface TransferMatchRequest {
    /**
     * BankTransaction id of one leg
     * @type {number}
     * @memberof TransferMatchRequest
     */
    transactionA: number;
    /**
     * BankTransaction id of the other leg
     * @type {number}
     * @memberof TransferMatchRequest
     */
    transactionB: number;
    /**
     * The leg the client was shown would be archived; a mismatch is refused with 409
     * @type {number}
     * @memberof TransferMatchRequest
     */
    expectedArchiveId: number;
}

/**
 * Check if a given object implements the TransferMatchRequest interface.
 */
export function instanceOfTransferMatchRequest(value: object): value is TransferMatchRequest {
    if (!('transactionA' in value) || value['transactionA'] === undefined) return false;
    if (!('transactionB' in value) || value['transactionB'] === undefined) return false;
    if (!('expectedArchiveId' in value) || value['expectedArchiveId'] === undefined) return false;
    return true;
}

export function TransferMatchRequestFromJSON(json: any): TransferMatchRequest {
    return TransferMatchRequestFromJSONTyped(json, false);
}

export function TransferMatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferMatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionA': json['transaction_a'],
        'transactionB': json['transaction_b'],
        'expectedArchiveId': json['expected_archive_id'],
    };
}

  export function TransferMatchRequestToJSON(json: any): TransferMatchRequest {
      return TransferMatchRequestToJSONTyped(json, false);
  }

  export function TransferMatchRequestToJSONTyped(value?: TransferMatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_a': value['transactionA'],
        'transaction_b': value['transactionB'],
        'expected_archive_id': value['expectedArchiveId'],
    };
}

