/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Dismiss a suggested pair as 'not a duplicate' so it stops being suggested.
 * @export
 * @interface TransferDismissRequest
 */
export interface TransferDismissRequest {
    /**
     * BankTransaction id of one leg
     * @type {number}
     * @memberof TransferDismissRequest
     */
    transactionA: number;
    /**
     * BankTransaction id of the other leg
     * @type {number}
     * @memberof TransferDismissRequest
     */
    transactionB: number;
}

/**
 * Check if a given object implements the TransferDismissRequest interface.
 */
export function instanceOfTransferDismissRequest(value: object): value is TransferDismissRequest {
    if (!('transactionA' in value) || value['transactionA'] === undefined) return false;
    if (!('transactionB' in value) || value['transactionB'] === undefined) return false;
    return true;
}

export function TransferDismissRequestFromJSON(json: any): TransferDismissRequest {
    return TransferDismissRequestFromJSONTyped(json, false);
}

export function TransferDismissRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransferDismissRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionA': json['transaction_a'],
        'transactionB': json['transaction_b'],
    };
}

  export function TransferDismissRequestToJSON(json: any): TransferDismissRequest {
      return TransferDismissRequestToJSONTyped(json, false);
  }

  export function TransferDismissRequestToJSONTyped(value?: TransferDismissRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'transaction_a': value['transactionA'],
        'transaction_b': value['transactionB'],
    };
}

