/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Serializer for a transaction to be created.
 * @export
 * @interface TransactionToCreate
 */
export interface TransactionToCreate {
    /**
     * Transaction date
     * @type {Date}
     * @memberof TransactionToCreate
     */
    date: Date;
    /**
     * Transaction description
     * @type {string}
     * @memberof TransactionToCreate
     */
    description: string | null;
    /**
     * Payee name
     * @type {string}
     * @memberof TransactionToCreate
     */
    payee: string | null;
    /**
     * Transaction amount
     * @type {string}
     * @memberof TransactionToCreate
     */
    amount: string;
    /**
     * Category account ID (for auto-categorization)
     * @type {number}
     * @memberof TransactionToCreate
     */
    categoryId?: number | null;
    /**
     * Whether to skip this transaction
     * @type {boolean}
     * @memberof TransactionToCreate
     */
    skip?: boolean;
}

/**
 * Check if a given object implements the TransactionToCreate interface.
 */
export function instanceOfTransactionToCreate(value: object): value is TransactionToCreate {
    if (!('date' in value) || value['date'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('payee' in value) || value['payee'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    return true;
}

export function TransactionToCreateFromJSON(json: any): TransactionToCreate {
    return TransactionToCreateFromJSONTyped(json, false);
}

export function TransactionToCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionToCreate {
    if (json == null) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'description': json['description'],
        'payee': json['payee'],
        'amount': json['amount'],
        'categoryId': json['category_id'] == null ? undefined : json['category_id'],
        'skip': json['skip'] == null ? undefined : json['skip'],
    };
}

  export function TransactionToCreateToJSON(json: any): TransactionToCreate {
      return TransactionToCreateToJSONTyped(json, false);
  }

  export function TransactionToCreateToJSONTyped(value?: TransactionToCreate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'date': ((value['date']).toISOString().substring(0,10)),
        'description': value['description'],
        'payee': value['payee'],
        'amount': value['amount'],
        'category_id': value['categoryId'],
        'skip': value['skip'],
    };
}

