/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionsBatchDelete200Response
 */
export interface TransactionsBatchDelete200Response {
    /**
     * 
     * @type {Array<number>}
     * @memberof TransactionsBatchDelete200Response
     */
    deleted?: Array<number>;
}

/**
 * Check if a given object implements the TransactionsBatchDelete200Response interface.
 */
export function instanceOfTransactionsBatchDelete200Response(value: object): value is TransactionsBatchDelete200Response {
    return true;
}

export function TransactionsBatchDelete200ResponseFromJSON(json: any): TransactionsBatchDelete200Response {
    return TransactionsBatchDelete200ResponseFromJSONTyped(json, false);
}

export function TransactionsBatchDelete200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionsBatchDelete200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'deleted': json['deleted'] == null ? undefined : json['deleted'],
    };
}

  export function TransactionsBatchDelete200ResponseToJSON(json: any): TransactionsBatchDelete200Response {
      return TransactionsBatchDelete200ResponseToJSONTyped(json, false);
  }

  export function TransactionsBatchDelete200ResponseToJSONTyped(value?: TransactionsBatchDelete200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted': value['deleted'],
    };
}

