/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response serializer for the upload_confirm endpoint.
 * @export
 * @interface UploadConfirmResponse
 */
export interface UploadConfirmResponse {
    /**
     * Number of transactions created
     * @type {number}
     * @memberof UploadConfirmResponse
     */
    createdCount: number;
    /**
     * Number of transactions skipped
     * @type {number}
     * @memberof UploadConfirmResponse
     */
    skippedCount: number;
    /**
     * Number of transactions with errors
     * @type {number}
     * @memberof UploadConfirmResponse
     */
    errorCount: number;
}

/**
 * Check if a given object implements the UploadConfirmResponse interface.
 */
export function instanceOfUploadConfirmResponse(value: object): value is UploadConfirmResponse {
    if (!('createdCount' in value) || value['createdCount'] === undefined) return false;
    if (!('skippedCount' in value) || value['skippedCount'] === undefined) return false;
    if (!('errorCount' in value) || value['errorCount'] === undefined) return false;
    return true;
}

export function UploadConfirmResponseFromJSON(json: any): UploadConfirmResponse {
    return UploadConfirmResponseFromJSONTyped(json, false);
}

export function UploadConfirmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadConfirmResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdCount': json['created_count'],
        'skippedCount': json['skipped_count'],
        'errorCount': json['error_count'],
    };
}

  export function UploadConfirmResponseToJSON(json: any): UploadConfirmResponse {
      return UploadConfirmResponseToJSONTyped(json, false);
  }

  export function UploadConfirmResponseToJSONTyped(value?: UploadConfirmResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_count': value['createdCount'],
        'skipped_count': value['skippedCount'],
        'error_count': value['errorCount'],
    };
}

