/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InvalidDateSample } from './InvalidDateSample';
import {
    InvalidDateSampleFromJSON,
    InvalidDateSampleFromJSONTyped,
    InvalidDateSampleToJSON,
    InvalidDateSampleToJSONTyped,
} from './InvalidDateSample';

/**
 * Response serializer for the upload_validate_dates endpoint.
 * @export
 * @interface UploadValidateDatesResponse
 */
export interface UploadValidateDatesResponse {
    /**
     * Total number of data rows checked
     * @type {number}
     * @memberof UploadValidateDatesResponse
     */
    totalRows: number;
    /**
     * Number of rows whose date cell failed to parse
     * @type {number}
     * @memberof UploadValidateDatesResponse
     */
    invalidCount: number;
    /**
     * Up to 5 example rows that failed, for the warning message
     * @type {Array<InvalidDateSample>}
     * @memberof UploadValidateDatesResponse
     */
    invalidSamples: Array<InvalidDateSample>;
    /**
     * A strftime format that would parse every non-blank date, if one exists
     * @type {string}
     * @memberof UploadValidateDatesResponse
     */
    suggestedFormat: string | null;
    /**
     * Error message if the file could not be read
     * @type {string}
     * @memberof UploadValidateDatesResponse
     */
    error: string | null;
}

/**
 * Check if a given object implements the UploadValidateDatesResponse interface.
 */
export function instanceOfUploadValidateDatesResponse(value: object): value is UploadValidateDatesResponse {
    if (!('totalRows' in value) || value['totalRows'] === undefined) return false;
    if (!('invalidCount' in value) || value['invalidCount'] === undefined) return false;
    if (!('invalidSamples' in value) || value['invalidSamples'] === undefined) return false;
    if (!('suggestedFormat' in value) || value['suggestedFormat'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function UploadValidateDatesResponseFromJSON(json: any): UploadValidateDatesResponse {
    return UploadValidateDatesResponseFromJSONTyped(json, false);
}

export function UploadValidateDatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadValidateDatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalRows': json['total_rows'],
        'invalidCount': json['invalid_count'],
        'invalidSamples': ((json['invalid_samples'] as Array<any>).map(InvalidDateSampleFromJSON)),
        'suggestedFormat': json['suggested_format'],
        'error': json['error'],
    };
}

  export function UploadValidateDatesResponseToJSON(json: any): UploadValidateDatesResponse {
      return UploadValidateDatesResponseToJSONTyped(json, false);
  }

  export function UploadValidateDatesResponseToJSONTyped(value?: UploadValidateDatesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_rows': value['totalRows'],
        'invalid_count': value['invalidCount'],
        'invalid_samples': ((value['invalidSamples'] as Array<any>).map(InvalidDateSampleToJSON)),
        'suggested_format': value['suggestedFormat'],
        'error': value['error'],
    };
}

