/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response serializer for the upload_parse endpoint.
 * @export
 * @interface UploadParseResponse
 */
export interface UploadParseResponse {
    /**
     * Column headers from the file
     * @type {Array<string>}
     * @memberof UploadParseResponse
     */
    headers: Array<string>;
    /**
     * Sample data rows (up to 5)
     * @type {Array<Array<string>>}
     * @memberof UploadParseResponse
     */
    sampleRows: Array<Array<string>>;
    /**
     * Total number of data rows
     * @type {number}
     * @memberof UploadParseResponse
     */
    totalRows: number;
    /**
     * Error message if parsing failed
     * @type {string}
     * @memberof UploadParseResponse
     */
    error: string | null;
}

/**
 * Check if a given object implements the UploadParseResponse interface.
 */
export function instanceOfUploadParseResponse(value: object): value is UploadParseResponse {
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('sampleRows' in value) || value['sampleRows'] === undefined) return false;
    if (!('totalRows' in value) || value['totalRows'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function UploadParseResponseFromJSON(json: any): UploadParseResponse {
    return UploadParseResponseFromJSONTyped(json, false);
}

export function UploadParseResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadParseResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'headers': json['headers'],
        'sampleRows': json['sample_rows'],
        'totalRows': json['total_rows'],
        'error': json['error'],
    };
}

  export function UploadParseResponseToJSON(json: any): UploadParseResponse {
      return UploadParseResponseToJSONTyped(json, false);
  }

  export function UploadParseResponseToJSONTyped(value?: UploadParseResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headers': value['headers'],
        'sample_rows': value['sampleRows'],
        'total_rows': value['totalRows'],
        'error': value['error'],
    };
}

