/* tslint:disable */
/* eslint-disable */
/**
 * Koala Budget
 * Budgeting and expense tracking app for freelancers
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionToCreate } from './TransactionToCreate';
import {
    TransactionToCreateFromJSON,
    TransactionToCreateFromJSONTyped,
    TransactionToCreateToJSON,
    TransactionToCreateToJSONTyped,
} from './TransactionToCreate';

/**
 * Request serializer for the upload_confirm endpoint.
 * @export
 * @interface UploadConfirmRequest
 */
export interface UploadConfirmRequest {
    /**
     * Bank account ID to upload to
     * @type {number}
     * @memberof UploadConfirmRequest
     */
    accountId: number;
    /**
     * Transactions to create
     * @type {Array<TransactionToCreate>}
     * @memberof UploadConfirmRequest
     */
    transactions: Array<TransactionToCreate>;
    /**
     * Whether to skip potential duplicates
     * @type {boolean}
     * @memberof UploadConfirmRequest
     */
    skipDuplicates?: boolean;
}

/**
 * Check if a given object implements the UploadConfirmRequest interface.
 */
export function instanceOfUploadConfirmRequest(value: object): value is UploadConfirmRequest {
    if (!('accountId' in value) || value['accountId'] === undefined) return false;
    if (!('transactions' in value) || value['transactions'] === undefined) return false;
    return true;
}

export function UploadConfirmRequestFromJSON(json: any): UploadConfirmRequest {
    return UploadConfirmRequestFromJSONTyped(json, false);
}

export function UploadConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadConfirmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['account_id'],
        'transactions': ((json['transactions'] as Array<any>).map(TransactionToCreateFromJSON)),
        'skipDuplicates': json['skip_duplicates'] == null ? undefined : json['skip_duplicates'],
    };
}

  export function UploadConfirmRequestToJSON(json: any): UploadConfirmRequest {
      return UploadConfirmRequestToJSONTyped(json, false);
  }

  export function UploadConfirmRequestToJSONTyped(value?: UploadConfirmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_id': value['accountId'],
        'transactions': ((value['transactions'] as Array<any>).map(TransactionToCreateToJSON)),
        'skip_duplicates': value['skipDuplicates'],
    };
}

