# Generated by Django 5.2.8 on 2025-12-04 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.IntegerField(help_text='Account number (1000s for assets, 2000s for liabilities, etc.)')),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('income', 'Income'), ('expense', 'Expense'), ('equity', 'Equity'), ('opening_balance_equity', 'Opening Balance Equity')], max_length=30)),
                ('in_bank_feed', models.BooleanField(default=False, help_text='Display in transactions tab')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['account_number'],
                'unique_together': {('team', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Goal target amount', max_digits=15)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount saved so far', max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount remaining (calculated)', max_digits=15)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Can be positive or negative', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(help_text='The account being debited/credited', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgeting.account')),
                ('category', models.ForeignKey(help_text='The category/account for classification', on_delete=django.db.models.deletion.PROTECT, related_name='categorized_transactions', to='budgeting.account')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgeting.payee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month')),
                ('budgeted_amount', models.DecimalField(decimal_places=2, help_text='Planned budget amount', max_digits=15)),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, help_text='Actual amount spent (calculated)', max_digits=15)),
                ('available_amount', models.DecimalField(decimal_places=2, default=0, help_text='Remaining budget (calculated)', max_digits=15)),
                ('category_name', models.CharField(blank=True, help_text='Cached category name', max_length=200)),
                ('category', models.ForeignKey(help_text='Income or expense category', limit_choices_to={'account_type__in': ['income', 'expense']}, on_delete=django.db.models.deletion.CASCADE, to='budgeting.account')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-month', 'category__account_number'],
                'unique_together': {('team', 'month', 'category')},
            },
        ),
    ]
