# Generated by Django 5.2.8 on 2025-12-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0003_team_billing_details_last_changed_team_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_name', models.CharField(help_text='Account type (e.g., Asset, Liability, Income, Expense)', max_length=100)),
                ('subtype_name', models.CharField(help_text='Account subtype (e.g., Checking, Savings, Credit Card)', max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['type_name', 'subtype_name'],
                'unique_together': {('team', 'type_name', 'subtype_name')},
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('account_number', models.IntegerField(help_text='Account number (1000s for assets, 2000s for liabilities, etc.)')),
                ('has_feed', models.BooleanField(default=False, help_text='Whether this account has a bank feed')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
                ('account_type', models.ForeignKey(blank=True, help_text='Account type classification', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_by_type', to='budgeting.accounttype')),
                ('subtype', models.ForeignKey(blank=True, help_text='Account subtype classification', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts_by_subtype', to='budgeting.accounttype')),
            ],
            options={
                'ordering': ['account_number'],
                'unique_together': {('team', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Goal target amount', max_digits=15)),
                ('saved_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount saved so far', max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount remaining (calculated)', max_digits=15)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('team', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_posted', models.DateField(help_text='Date the transaction was posted')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('imported_on', models.DateField(blank=True, help_text='Date the transaction was imported', null=True)),
                ('import_method', models.CharField(choices=[('manual', 'Manual Entry'), ('csv', 'CSV Import'), ('api', 'API Import'), ('bank_feed', 'Bank Feed')], default='manual', help_text='How the transaction was imported', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('posted', 'Posted'), ('reconciled', 'Reconciled')], default='pending', help_text='Transaction status', max_length=20)),
                ('is_cleared', models.BooleanField(default=False, help_text='Whether the transaction has cleared')),
                ('is_reconciled', models.BooleanField(default=False, help_text='Whether the transaction has been reconciled')),
                ('account', models.ForeignKey(help_text='The account being debited/credited', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgeting.account')),
                ('category', models.ForeignKey(blank=True, help_text='The category/account for classification', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categorized_transactions', to='budgeting.account')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budgeting.payee')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-date_posted', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month')),
                ('budget', models.DecimalField(decimal_places=2, help_text='Planned budget amount', max_digits=15)),
                ('category', models.ForeignKey(help_text='Income or expense category (account)', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='budgeting.account')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-month', 'category__account_number'],
                'unique_together': {('team', 'month', 'category')},
            },
        ),
    ]
