# Generated by Django 6.0 on 2025-12-29 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rename_payee_id_payee_id'),
        ('teams', '0004_invitation_is_archived_membership_is_archived_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('month', models.DateField(help_text='First day of the month')),
                ('budget_amount', models.DecimalField(decimal_places=2, help_text='Planned budget amount', max_digits=15)),
                ('category', models.ForeignKey(help_text='Income or expense category (account)', on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounts.account')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-month', 'category__account_number'],
                'unique_together': {('team', 'month', 'category')},
            },
        ),
    ]
