# Generated by Django 6.0 on 2026-01-25 20:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accountgroup_account_type'),
        ('budget', '0001_initial'),
        ('teams', '0005_invitation_archived_at_membership_archived_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='Date this item was archived', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('target_amount', models.DecimalField(decimal_places=2, help_text='Target savings amount', max_digits=15, verbose_name='Target amount')),
                ('target_date', models.DateField(blank=True, help_text='Target date to reach the goal', null=True, verbose_name='Target date')),
                ('is_complete', models.BooleanField(default=False, help_text='Whether this goal has been completed', verbose_name='Completed')),
                ('is_archived', models.BooleanField(default=False, help_text='Whether this goal is archived', verbose_name='Archived')),
                ('order', models.IntegerField(default=0, help_text='Display order for goals', verbose_name='Order')),
                ('account', models.OneToOneField(blank=True, help_text='Associated equity account (automatically created)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goal', to='accounts.account', verbose_name='Account')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['order', 'target_date', 'name'],
                'default_related_name': 'budget_goals',
                'unique_together': {('team', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GoalAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Set to true to archive this item')),
                ('archived_at', models.DateTimeField(blank=True, help_text='Date this item was archived', null=True)),
                ('month', models.DateField(help_text='Month of this allocation (first day of month)', verbose_name='Month')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount allocated this month', max_digits=15, verbose_name='Amount')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='budget.goal', verbose_name='Goal')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
            options={
                'ordering': ['-month'],
                'default_related_name': 'budget_goal_allocations',
                'unique_together': {('team', 'goal', 'month')},
            },
        ),
    ]
