# Generated by Django 6.0 on 2026-05-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_goal_goalallocation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-month', 'category__name']},
        ),
    ]
