# Generated by Django 6.0 on 2026-06-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0002_goal_goalallocation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budget",
            options={"ordering": ["-month", "category__name"]},
        ),
    ]
