# Generated by Django 6.0 on 2026-09-24 15:49

from django.db import migrations, models

EQUITY = "goal"


def move_goal_accounts_out_of_system_groups(apps, schema_editor):
    """
    `Goal.save()` used to fall back to the lowest-id equity group when there was
    no "Goals" group -- on template and generated charts, the system "Equity
    Adjustments" group. Move those accounts into a non-system "Goals" group.
    A group change only; the account type is untouched.
    """
    Account = apps.get_model("accounts", "Account")
    AccountGroup = apps.get_model("accounts", "AccountGroup")

    stray = Account.objects.filter(goal__isnull=False, account_group__is_system=True).select_related("account_group")
    groups = {}
    for account in stray:
        team_id = account.team_id
        if team_id not in groups:
            group = AccountGroup.objects.filter(team_id=team_id, account_type=EQUITY, name="Goals", is_system=False).first()
            if group is None:
                name = "Goals"
                if AccountGroup.objects.filter(team_id=team_id, name=name).exists():
                    name = "Savings Goals"
                group = AccountGroup.objects.filter(
                    team_id=team_id, account_type=EQUITY, name=name, is_system=False
                ).first() or AccountGroup.objects.create(
                    team_id=team_id, account_type=EQUITY, name=name, description="Savings goals"
                )
            groups[team_id] = group
        account.account_group = groups[team_id]
        account.save(update_fields=["account_group"])


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0003_alter_budget_options"),
        ("accounts", "0008_add_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="closed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the goal was closed",
                null=True,
                verbose_name="Closed at",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="is_complete",
            field=models.BooleanField(
                default=False,
                help_text="Stop asking for money for this goal",
                verbose_name="Funded",
            ),
        ),
        migrations.RunPython(move_goal_accounts_out_of_system_groups, migrations.RunPython.noop),
    ]
