# Generated by Django 6.0 on 2026-10-01 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_account_hidden_from_budget"),
        ("books", "0003_backfill_books"),
        ("budget", "0006_book_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="monthly_contribution",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="How much you plan to put towards the goal each month",
                max_digits=15,
                null=True,
                verbose_name="Monthly contribution",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="outflow",
            field=models.CharField(
                choices=[
                    ("withdraw", "Take it out of the goal"),
                    ("spend", "Count it as spent from the goal"),
                    ("ignore", "Leave the goal alone"),
                ],
                default="withdraw",
                help_text="What money leaving a linked account for one of your other accounts does to the goal",
                max_length=10,
                verbose_name="When money moves out",
            ),
        ),
        migrations.CreateModel(
            name="GoalAccountLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Set to true to archive this item"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="Date this item was archived", null=True
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        help_text="First day counted", verbose_name="Count from"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Last day counted",
                        null=True,
                        verbose_name="Until",
                    ),
                ),
                (
                    "include_starting_balance",
                    models.BooleanField(
                        default=True,
                        help_text="Count the account's balance on the day before the start date towards the goal",
                        verbose_name="Include the balance already there",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="goal_links",
                        to="accounts.account",
                        verbose_name="Account",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_links",
                        to="budget.goal",
                        verbose_name="Goal",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date", "pk"],
                "default_related_name": "budget_goal_account_links",
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("end_date__isnull", True)),
                        fields=("book", "account"),
                        name="goal_account_link_one_open_per_account",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_date__isnull", True),
                            ("end_date__gte", models.F("start_date")),
                            _connector="OR",
                        ),
                        name="goal_account_link_end_after_start",
                    ),
                ],
            },
        ),
    ]
