# Generated by Django 6.0 on 2026-10-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0007_goal_account_links"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="target_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Target savings amount (0 for an open-ended goal)",
                max_digits=15,
                verbose_name="Target amount",
            ),
        ),
    ]
