# Generated by Django 6.0 on 2026-10-08 20:20

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def adopt_existing_goals(apps, schema_editor):
    """Plans start this month for every goal that already exists, so no earlier
    month changes (docs/goal-plans-plan.md §3.3)."""
    from apps.budget.plans import adopt_goals

    Goal = apps.get_model("budget", "Goal")
    GoalPlan = apps.get_model("budget", "GoalPlan")
    GoalAllocation = apps.get_model("budget", "GoalAllocation")
    GoalAccountLink = apps.get_model("budget", "GoalAccountLink")
    adopt_goals(
        Goal.objects.all(),
        timezone.localdate().replace(day=1),
        Goal=Goal,
        GoalPlan=GoalPlan,
        GoalAllocation=GoalAllocation,
        GoalAccountLink=GoalAccountLink,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_backfill_books"),
        ("budget", "0008_goal_target_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="plan_from",
            field=models.DateField(
                blank=True,
                help_text="First month the current monthly contribution applies to (first day of month)",
                null=True,
                verbose_name="Plan from",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="unmet_plan",
            field=models.CharField(
                choices=[
                    ("release", "Release it at the end of the month"),
                    ("carry", "Keep holding it until the money arrives"),
                ],
                default="release",
                help_text="What happens to money planned for this goal that hasn't reached its linked accounts by month end",
                max_length=10,
                verbose_name="When planned money isn't moved",
            ),
        ),
        migrations.CreateModel(
            name="GoalPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="Set to true to archive this item"
                    ),
                ),
                (
                    "archived_at",
                    models.DateTimeField(
                        blank=True, help_text="Date this item was archived", null=True
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        help_text="Month of this plan (first day of month)",
                        verbose_name="Month",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount planned for the month",
                        max_digits=15,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("default", "Monthly contribution"),
                            ("typed", "Changed for this month"),
                        ],
                        default="typed",
                        max_length=10,
                        verbose_name="Source",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.book",
                        verbose_name="Book",
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="budget.goal",
                        verbose_name="Goal",
                    ),
                ),
            ],
            options={
                "ordering": ["goal", "month"],
                "default_related_name": "budget_goal_plans",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gte", 0)),
                        name="goal_plan_amount_not_negative",
                    )
                ],
                "unique_together": {("book", "goal", "month")},
            },
        ),
        migrations.RunPython(adopt_existing_goals, migrations.RunPython.noop),
    ]
