# Generated by Django 5.2.8 on 2025-12-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams_example', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Set to true to archive this item'),
        ),
    ]
