# Generated by Django 5.2.8 on 2025-12-16 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_agent_type_chat_chat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Set to true to archive this item'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Set to true to archive this item'),
        ),
    ]
